export const pvpAchievementDefinitions = [
  {
    "id": "ACH_P01",
    "name": "两锋相见",
    "condition": "完成首次合格完整PVP胜负结算",
    "rarity": "普通",
    "attribute": "体质+1",
    "description": "你的对面，站着另一种答案。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P02",
    "name": "胜负初分",
    "condition": "首次合格PVP获胜",
    "rarity": "普通",
    "attribute": "力量+1",
    "description": "风停下来时，你仍握着自己的剑。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P03",
    "name": "五次回响",
    "condition": "合格PVP获胜5次",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "description": "锋刃记住了不同的回声。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P04",
    "name": "交锋成章",
    "condition": "合格PVP获胜20次",
    "rarity": "精良",
    "attribute": "力量+3",
    "description": "零散的胜负，终于连成了你的篇章。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P05",
    "name": "百折锋芒",
    "condition": "合格PVP获胜50次",
    "rarity": "稀有",
    "attribute": "体质+5",
    "description": "磨损留在剑上，锋芒留在你心里。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P06",
    "name": "百战有名",
    "condition": "合格PVP获胜100次",
    "rarity": "传说",
    "attribute": "力量+8",
    "description": "你的名字，开始先于脚步抵达。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P07",
    "name": "三种答案",
    "condition": "合格战胜3个不同身份的玩家",
    "rarity": "优秀",
    "attribute": "感知+2",
    "description": "每一双眼睛，都有不同的锋芒。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P08",
    "name": "十面来风",
    "condition": "合格战胜10个不同身份的玩家",
    "rarity": "精良",
    "attribute": "感知+3",
    "description": "十面来风，你站在风的中央。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P09",
    "name": "众锋之间",
    "condition": "合格战胜25个不同身份的玩家",
    "rarity": "稀有",
    "attribute": "敏捷+5",
    "description": "人群的锋芒，没有淹没你的轮廓。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P10",
    "name": "寸步不让",
    "condition": "作为防守方首次合格获胜",
    "rarity": "普通",
    "attribute": "体质+1",
    "description": "这一步，是你留给世界的边界。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P11",
    "name": "门前五战",
    "condition": "作为防守方合格获胜5次",
    "rarity": "优秀",
    "attribute": "精神+2",
    "description": "来者更替，你身后的灯没有熄。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P12",
    "name": "不动之界",
    "condition": "作为防守方合格获胜20次",
    "rarity": "精良",
    "attribute": "体质+3",
    "description": "风暴走过，边界仍在原处。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P13",
    "name": "剑先于言",
    "condition": "作为进攻方首次合格获胜",
    "rarity": "普通",
    "attribute": "力量+1",
    "description": "你让锋刃替自己说完了第一句话。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P14",
    "name": "十步问锋",
    "condition": "作为进攻方合格获胜10次",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "description": "每向前一步，都有新的答案。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P15",
    "name": "破阵之人",
    "condition": "作为进攻方合格获胜30次",
    "rarity": "精良",
    "attribute": "力量+3",
    "description": "阻挡过你的事物，成了身后的远景。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P16",
    "name": "三日磨剑",
    "condition": "在3个不同自然日完成合格PVP胜负结算",
    "rarity": "优秀",
    "attribute": "精神+2",
    "description": "昨日留下的痕迹，今天仍在发亮。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P17",
    "name": "七日不锈",
    "condition": "在7个不同自然日完成合格PVP胜负结算",
    "rarity": "精良",
    "attribute": "精神+3",
    "description": "日子向前，锋刃没有生锈。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P18",
    "name": "月下常锋",
    "condition": "在30个不同自然日完成合格PVP胜负结算",
    "rarity": "稀有",
    "attribute": "精神+5",
    "description": "一轮月亮看过了你的许多次归来。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P20",
    "name": "同阶争鸣",
    "condition": "合格战胜同级玩家10次",
    "rarity": "优秀",
    "attribute": "智力+2",
    "description": "相近的高度，仍能走出不同的距离。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P22",
    "name": "越阶而行",
    "condition": "合格战胜高于本人至少2级的玩家5次",
    "rarity": "精良",
    "attribute": "智力+3",
    "description": "台阶很高，你仍留下了向上的足迹。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P23",
    "name": "余烬未冷",
    "condition": "合格PVP胜利时自身HP大于0且不超过最大HP的10%",
    "rarity": "精良",
    "attribute": "体质+3",
    "description": "余下的一点火，足够照亮胜负。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P24",
    "name": "长夜决锋",
    "condition": "完成至少10回合的合格PVP并获胜",
    "rarity": "精良",
    "attribute": "精神+3",
    "description": "长夜磨尽了喧嚣，留下最后的站立。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  },
  {
    "id": "ACH_P25",
    "name": "五地留锋",
    "condition": "在5个不同正式地区取得合格PVP胜利",
    "rarity": "稀有",
    "attribute": "感知+5",
    "description": "地图上的远方，也记住了你的锋芒。",
    "scope": "累",
    "dependency": "现",
    "category": "PVP"
  }
];
export const pvpAchievementThresholds:Record<string,number> = {
  "P01": 1,
  "P02": 1,
  "P03": 5,
  "P04": 20,
  "P05": 50,
  "P06": 100,
  "P07": 3,
  "P08": 10,
  "P09": 25,
  "P10": 1,
  "P11": 5,
  "P12": 20,
  "P13": 1,
  "P14": 10,
  "P15": 30,
  "P16": 3,
  "P17": 7,
  "P18": 30,
  "P20": 10,
  "P22": 5,
  "P23": 1,
  "P24": 1,
  "P25": 5
};
