import { surpriseAchievementDefinitions } from './achievement-surprise.config';
import { challengeAchievementDefinitions } from './achievement-challenge.config';
import { retiredAchievementIdSet } from './achievement-retired.config';
import { easterAchievementDefinitions } from './achievement-easter.config';
import { pvpAchievementDefinitions } from './achievement-pvp.config';
// 维护条件保留在服务端；消息必须使用显式投影。
export const achievementCategories = ["全部","初行","战斗","技战","探索","收藏","交涉","同行","采炼","锻造","机巧","日常","剧情","PVP","首领","秘闻"] as const;
const baseAchievementDefinitions = [
  {
    "id": "ACH_A01",
    "name": "此身入世",
    "description": "世界翻开新的一页，你的名字落了下来。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "完成一次正式角色注册与开局落地",
    "scope": "场",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A02",
    "name": "名字写在纸上",
    "description": "纸上的墨会干，走过的路不会。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "完成首次冒险者登记",
    "scope": "场",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A03",
    "name": "手中有刃",
    "description": "握紧的那一刻，陌生的重量有了归处。",
    "rarity": "普通",
    "attribute": "力量+1",
    "condition": "首次装备一件符合资格的武器",
    "scope": "场",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A04",
    "name": "不再赤手空拳",
    "description": "风碰到你时，终于听见了回声。",
    "rarity": "普通",
    "attribute": "智力+1",
    "condition": "在一次出战快照中实际装备武器及至少一件防具",
    "scope": "场",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A05",
    "name": "第一门手艺",
    "description": "手掌记住了另一种改变世界的方法。",
    "rarity": "普通",
    "attribute": "敏捷+1",
    "condition": "本世正式学会一门普通副职业或完成一艺入门",
    "scope": "世",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A06",
    "name": "学会出招",
    "description": "意念第一次找到了自己的形状。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "首次合法学会一项可使用的普通技能或仙路战技/神通",
    "scope": "场",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A07",
    "name": "温故知新",
    "description": "旧日的招式里，长出了新的回答。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "首次完成一次付费技能升级",
    "scope": "场",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A08",
    "name": "术有专攻",
    "description": "道路开始分岔，你听清了其中一条。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "首次合法投入一次普通技能专精",
    "scope": "场",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A09",
    "name": "四种思路",
    "description": "同一束光，也可以照出不同的方向。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "本世分别实际使用过四种普通技能专精的合法配置",
    "scope": "世",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A10",
    "name": "重新整理行囊",
    "description": "放下不是遗忘，是为下一次握紧。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "完成一次合法技能重置并重新学习一项技能",
    "scope": "世",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A11",
    "name": "五级之约",
    "description": "鞋底的泥，已不全来自故乡。",
    "rarity": "普通",
    "attribute": "敏捷+1",
    "condition": "本世到达普通Lv.5或特殊路线对应已开放实力节点",
    "scope": "世",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A12",
    "name": "初窥门径",
    "description": "门后的风，终于吹到了你身上。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "本世到达Lv.10对应实力节点",
    "scope": "世",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A13",
    "name": "更远的地方",
    "description": "昨天遥远的地方，今天留有你的足迹。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "本世到达Lv.20对应实力节点",
    "scope": "世",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A14",
    "name": "三十而行",
    "description": "来时的山，已成身后的风景。",
    "rarity": "稀有",
    "attribute": "精神+5",
    "condition": "本世到达Lv.30对应实力节点",
    "scope": "世",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A15",
    "name": "第一道门",
    "description": "有些门，只认亲手推开它的人。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "首次通过本人路线的正式大阶段晋境",
    "scope": "场",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A16",
    "name": "自己的职业",
    "description": "你选择的名字，开始有了重量。",
    "rarity": "普通",
    "attribute": "智力+1",
    "condition": "本世正式选择一次普通一转职业",
    "scope": "世",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A17",
    "name": "更深一层",
    "description": "旧路尽头，又传来一声召唤。",
    "rarity": "精良",
    "attribute": "敏捷+3",
    "condition": "本世完成普通二转的正式资格与选择",
    "scope": "世",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A18",
    "name": "行家入门",
    "description": "生疏的声响，渐渐成为节奏。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "本世任一普通副职业达到Lv.3",
    "scope": "世",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A19",
    "name": "熟能生巧",
    "description": "手比言语更早懂得其中的道理。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "本世任一普通副职业达到Lv.5",
    "scope": "世",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A20",
    "name": "炉边十年",
    "description": "炉火会熄，掌中的分寸不会。",
    "rarity": "传说",
    "attribute": "精神+8",
    "condition": "本世任一普通副职业达到当前Lv.11上限",
    "scope": "世",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A21",
    "name": "鉴识初成",
    "description": "雾退去一点，世界便多出一层纹理。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "本世鉴识能力完成首次合法提升",
    "scope": "世",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A22",
    "name": "兵器相知",
    "description": "它不再只是一件兵器。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "本世一项武器专精完成首次合法提升",
    "scope": "世",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_A23",
    "name": "别来无恙",
    "description": "醒来以后，前路仍等着你的脚步。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "首次PVE战败醒来后，完成一场合格PVE胜利",
    "scope": "世",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A24",
    "name": "七日行旅",
    "description": "日子散落着，你把它们拾成一条路。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "在7个不同自然日完成至少一项战斗/采集/制作/正式任务",
    "scope": "累",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A25",
    "name": "三十日见闻",
    "description": "风翻过许多页，你始终没有缺席。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "在30个不同自然日完成上述真实活动，不要求连续",
    "scope": "累",
    "dependency": "扩",
    "category": "初行"
  },
  {
    "id": "ACH_A26",
    "name": "宁静的彼岸",
    "description": "你没有踏上未知的土地，却认真地为自己选择了一段安稳的时光。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "在神界选择前往天堂，并完成最后的告别。",
    "scope": "累",
    "dependency": "现",
    "category": "初行"
  },
  {
    "id": "ACH_B01",
    "name": "第一滴血",
    "description": "刃上的红，是命运第一次回答。",
    "rarity": "普通",
    "attribute": "力量+1",
    "condition": "首次本人实际击杀正式PVE敌人，降服不计",
    "scope": "场",
    "dependency": "扩",
    "category": "战斗"
  },
  {
    "id": "ACH_B02",
    "name": "初战告捷",
    "description": "风还未停，你已经站到了最后。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "首次取得合格PVE胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B03",
    "name": "十战磨锋",
    "description": "锋芒渐定，手心仍有初时的热。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "合格PVE胜利10场",
    "scope": "累",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B04",
    "name": "百战余温",
    "description": "尘土认得你的脚步，敌人记住你的沉默。",
    "rarity": "精良",
    "attribute": "力量+3",
    "condition": "合格PVE胜利100场",
    "scope": "累",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B05",
    "name": "千战行者",
    "description": "岁月磨去浮光，留下不会折断的锋。",
    "rarity": "传说",
    "attribute": "力量+8",
    "condition": "合格PVE胜利1000场",
    "scope": "累",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B06",
    "name": "精英初遇",
    "description": "庞大的影子，也会在脚下倒下。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "首次合格击败精英敌人",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B07",
    "name": "狩猎精英",
    "description": "那些曾让人绕路的名字，成了旧闻。",
    "rarity": "精良",
    "attribute": "力量+3",
    "condition": "合格击败20个不同生命实例的精英",
    "scope": "累",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B08",
    "name": "越过首领",
    "description": "山岳低下头时，你仍握着武器。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "首次参与合格首领胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B09",
    "name": "首领见证人",
    "description": "每一道巨影身后，都有一段归途。",
    "rarity": "稀有",
    "attribute": "敏捷+5",
    "condition": "击败5种不同正式首领模板",
    "scope": "种",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B10",
    "name": "旧敌新知",
    "description": "陌生的吼声，渐渐有了熟悉的轮廓。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "击败10种不同正式敌人模板",
    "scope": "种",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B11",
    "name": "百怪行记",
    "description": "世界披过许多獠牙，你都曾与之相望。",
    "rarity": "稀有",
    "attribute": "体质+5",
    "condition": "击败100种不同正式敌人模板",
    "scope": "种",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B12",
    "name": "林间止戈",
    "description": "林叶一颤，战意落进泥土。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "在幽暗密林取得首次合格胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B13",
    "name": "深林回声",
    "description": "越过树影，深处终于有了回声。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "在幽暗密林深处取得首次合格胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B14",
    "name": "砾风之刃",
    "description": "风裹着石屑，也裹不住你的锋芒。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "在砾风石滩取得首次合格胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B15",
    "name": "山脊上的人",
    "description": "群山无言，替你记下一次站立。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "在岩脊山麓取得首次合格胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B16",
    "name": "赤铁余火",
    "description": "余火映在铁色的路上，久久不灭。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "在赤铁山道取得首次合格胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B17",
    "name": "湿地回响",
    "description": "水雾散开，留下仍然向前的人。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "在雾藻湿地取得首次合格胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B18",
    "name": "沉星不眠",
    "description": "星光沉入泥底，目光却没有低下。",
    "rarity": "精良",
    "attribute": "敏捷+3",
    "condition": "在沉星沼泽取得首次合格胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B19",
    "name": "霜冠试锋",
    "description": "霜雪压住衣角，压不住归来的脚步。",
    "rarity": "精良",
    "attribute": "力量+3",
    "condition": "在霜冠高原取得首次合格胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B20",
    "name": "听雷而战",
    "description": "雷声落地以前，你已给出回答。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "在雷鸣断崖取得首次合格胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B21",
    "name": "月蚀之后",
    "description": "缺月照旧刃，长夜不再只有阴影。",
    "rarity": "精良",
    "attribute": "敏捷+3",
    "condition": "在月蚀遗迹取得首次合格胜利",
    "scope": "场",
    "dependency": "现",
    "category": "战斗"
  },
  {
    "id": "ACH_B22",
    "name": "一敌多形",
    "description": "庞然之物的裂隙，被你听见了。",
    "rarity": "精良",
    "attribute": "力量+3",
    "condition": "在一场多部位首领战中对2个不同有效部位造成实际伤害并胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "战斗"
  },
  {
    "id": "ACH_B23",
    "name": "先折其翼",
    "description": "不可一世的羽翼，终于落进尘埃。",
    "rarity": "稀有",
    "attribute": "体质+5",
    "condition": "在有对应规则的首领战中，先破坏指定部位再击败本体",
    "scope": "场",
    "dependency": "扩",
    "category": "战斗"
  },
  {
    "id": "ACH_B24",
    "name": "重整旗鼓",
    "description": "同一阵风，这次没能把你吹倒。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "同一生命实例上战败或撤退后，合法再次挑战并取得胜利",
    "scope": "世",
    "dependency": "扩",
    "category": "战斗"
  },
  {
    "id": "ACH_B25",
    "name": "归来仍少年",
    "description": "直到巨影散去，衣上的晨光仍在。",
    "rarity": "稀有",
    "attribute": "力量+5",
    "condition": "本世首次首领胜利前未触发任何PVE战败结算",
    "scope": "世",
    "dependency": "扩",
    "category": "战斗"
  },
  {
    "id": "ACH_C01",
    "name": "抓住破绽",
    "description": "裂隙出现的一瞬，锋芒已经抵达。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "首次实际造成一次PVE暴击",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C02",
    "name": "擦肩而过",
    "description": "死神擦过衣角，带走的只有风。",
    "rarity": "普通",
    "attribute": "敏捷+1",
    "condition": "首次在正式PVE中闪避一次敌方直击",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C03",
    "name": "举盾之时",
    "description": "退半步的身后，是不肯让出的地方。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "一次主动防御实际降低本次受击伤害",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C04",
    "name": "盾还在",
    "description": "看不见的墙，也有守住什么的重量。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "本人的护盾首次实际吸收敌方伤害",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C05",
    "name": "不让你倒下",
    "description": "坠落的名字，被你接回人间。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "对低于30%最大HP的队友完成一次有效技能治疗",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C06",
    "name": "自救有方",
    "description": "命悬一线时，你仍握住了那根线。",
    "rarity": "普通",
    "attribute": "力量+1",
    "condition": "本人在低于30%HP时使用合法恢复品取得实际回复并赢得该战",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C07",
    "name": "尘毒尽去",
    "description": "阴翳散尽，呼吸重新变得清澈。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "在正式PVE中净化一次可净化DOT",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C08",
    "name": "封住这一招",
    "description": "未出口的恶意，停在了喉间。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "用合法打断机制实际中断一次敌方吟唱",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C09",
    "name": "趁其未发",
    "description": "灾厄尚在酝酿，结局已经改写。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "在敌方已公开预告的高威力行动结算前击败该敌并获胜",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C10",
    "name": "破盾者",
    "description": "坚固不是永恒，裂纹终会回答。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "本人实际打空一次敌方正值护盾",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C11",
    "name": "余烬收尾",
    "description": "火焰退去以后，余温仍记得敌人。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "本人施加的DOT造成正式敌人的最后实际HP损失并获胜",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C12",
    "name": "一式双响",
    "description": "一线锋光，照亮不止一处阴影。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "一次合法范围行动实际命中2个不同正式敌人",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C13",
    "name": "三方受敌",
    "description": "四面皆是来敌，脚下仍有立足之地。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "一场面对至少3名正式敌人的战斗中取得胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C14",
    "name": "以小博大",
    "description": "高处的影子，没能遮住你的目光。",
    "rarity": "精良",
    "attribute": "敏捷+3",
    "condition": "击败兼容等级高于本人至少2级的非教学正式敌人",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C15",
    "name": "留一口气",
    "description": "世界只剩微弱一线，你仍没有松手。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "获胜时本人HP大于0且不超过最大HP的10%，排除刻意友方伤害",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C16",
    "name": "仍有余力",
    "description": "风暴过去，掌心还留着余温。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "完成至少5次本人正常行动的胜利，结束时MP不少于50%",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C17",
    "name": "全身而退",
    "description": "衣角拂过刀光，归来仍无伤痕。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "独自赢得同级以上非教学PVE且实际HP损失为0，敌方至少行动一次",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C18",
    "name": "不借药力",
    "description": "没有借来的春水，生命依然向前。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "一场至少5次本人正常行动的胜利中未受恢复药剂效果",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C19",
    "name": "变招之人",
    "description": "你的答案，不止一种形状。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "一场胜利中实际使用攻击、防御、支援三种动作，各至少1次",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C20",
    "name": "见机行事",
    "description": "风每换一个方向，你便换一种站法。",
    "rarity": "精良",
    "attribute": "敏捷+3",
    "condition": "一场战斗成功应对两个不同预告机制并获胜",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C21",
    "name": "火候正好",
    "description": "炽热的意志，留在锋芒经过之处。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "在一场胜利中对同一敌人实际施加火系伤害与合法灼烧",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C22",
    "name": "水落石出",
    "description": "同一场雨，也能落出不同的声音。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "在一场胜利中造成两种不同伤害元素的实际直击",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C23",
    "name": "收放自如",
    "description": "取与舍之间，力量学会了流动。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "使用有记录的资源生成技能，再成功支付该资源施放另一技能",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C24",
    "name": "反手一击",
    "description": "对方递来的锋刃，带回了你的回答。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "合法反击对正式敌人造成实际HP损失并最终获胜",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_C25",
    "name": "守到最后",
    "description": "直到最后一声回响，你仍在众人之前。",
    "rarity": "精良",
    "attribute": "感知+3",
    "condition": "同一首领战中本人存活，实际完成防御、治疗或护盾贡献至少3次",
    "scope": "场",
    "dependency": "扩",
    "category": "技战"
  },
  {
    "id": "ACH_D01",
    "name": "第一步之外",
    "description": "故乡在身后，世界在脚下展开。",
    "rarity": "普通",
    "attribute": "敏捷+1",
    "condition": "首次通过合法旅行进入出生地区以外的区域",
    "scope": "场",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D02",
    "name": "树荫之下",
    "description": "古老的枝叶，替远来的人留下一片阴凉。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "实际抵达世界树并完成一次合法地点交互",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D03",
    "name": "百纳百客",
    "description": "人声深处，有一条路记住了你的名字。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "实际抵达百纳镇并完成一次合法地点交互",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D04",
    "name": "草原环带",
    "description": "长风越过草浪，也越过你的肩头。",
    "rarity": "普通",
    "attribute": "敏捷+1",
    "condition": "实际抵达世界树草原环带",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D05",
    "name": "晨露沾衣",
    "description": "晨露未干，远行已经开始。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "实际抵达晨露河岸",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D06",
    "name": "石滩来信",
    "description": "石间的风，把海的旧事讲给你听。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "实际抵达砾风石滩",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D07",
    "name": "林深处见",
    "description": "树影层层合拢，你仍看见前路。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "实际抵达幽暗密林深处",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D08",
    "name": "踏上岩脊",
    "description": "山脊托起脚步，也托起更远的目光。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "实际抵达岩脊山麓",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D09",
    "name": "铁色山风",
    "description": "铁色的风，把衣角染成远行的颜色。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "实际抵达赤铁山道",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D10",
    "name": "藻间小径",
    "description": "薄雾让开一寸，水草便露出旧路。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "实际抵达雾藻湿地",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D11",
    "name": "星沉脚下",
    "description": "脚下是泥，眼中仍有沉落的星。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "实际抵达沉星沼泽",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D12",
    "name": "冠上霜雪",
    "description": "寒意攀上群山，你走进它的冠冕。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "实际抵达霜冠高原",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D13",
    "name": "雷声很近",
    "description": "大地的心跳，在这里格外响亮。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "实际抵达雷鸣断崖",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D14",
    "name": "月缺之地",
    "description": "月光缺了一角，故事却多出一页。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "实际抵达月蚀遗迹",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D15",
    "name": "叶上人家",
    "description": "叶脉承起人间，云影从窗外经过。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "实际抵达浮叶镇并完成一次合法地点交互",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D16",
    "name": "一盏雪灯",
    "description": "一盏暖光，让雪原有了方向。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "实际抵达雪灯坳并完成一次合法地点交互",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D17",
    "name": "龙舍留客",
    "description": "陌生的屋檐，也可以接住旅人的疲惫。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "实际抵达霜龙客舍并完成一次合法地点交互",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D18",
    "name": "鲸背旅人",
    "description": "鲸的呼吸里，远方正缓缓靠岸。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "实际抵达眠鲸旅市并完成一次合法地点交互",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D19",
    "name": "四方来去",
    "description": "不同的风，开始在衣上相逢。",
    "rarity": "普通",
    "attribute": "敏捷+1",
    "condition": "正式到访4个不同区域，排除测试区",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D20",
    "name": "十地图志",
    "description": "地图折了又展，边缘仍有未尽的路。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "正式到访10个不同区域，排除测试区",
    "scope": "种",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D21",
    "name": "自己的路标",
    "description": "世界很大，你为自己留下一个记号。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "在合法位置建立本人首个地图标记",
    "scope": "场",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D22",
    "name": "再循旧路",
    "description": "记号没有移动，归来的人已看见更多。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "从异地合法走回本人已建立的标记并到达其有效范围",
    "scope": "场",
    "dependency": "扩",
    "category": "探索"
  },
  {
    "id": "ACH_D23",
    "name": "意外的发现",
    "description": "寻常的风景，忽然向你眨了一下眼。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "首次成为正式动态场景的发现者并完成有效调查",
    "scope": "场",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D24",
    "name": "不是路过",
    "description": "别人的故事里，也留下了你的分量。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "作为协助者实际完成另一人发现的动态场景贡献",
    "scope": "场",
    "dependency": "现",
    "category": "探索"
  },
  {
    "id": "ACH_D25",
    "name": "大地有声",
    "description": "大地从不沉默，只等愿意听见的人。",
    "rarity": "精良",
    "attribute": "敏捷+3",
    "condition": "完成5种不同正式动态场景模板的有效解决",
    "scope": "种",
    "dependency": "扩",
    "category": "探索"
  },
  {
    "id": "ACH_E01",
    "name": "第一页图鉴",
    "description": "空白的一页，终于有了第一道墨痕。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "首次实际发现一项图鉴条目，公开浏览不算发现",
    "scope": "场",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E02",
    "name": "十件小事",
    "description": "平凡的物件，也各自藏着来处。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "实际取得10种不同普通物品定义",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E03",
    "name": "百物随身",
    "description": "行囊盛不下世界，记忆可以多留一些。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "历来实际取得100种不同物品定义，不要求同时持有",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E04",
    "name": "百材识性",
    "description": "泥土与炉火的语言，渐渐变得清晰。",
    "rarity": "稀有",
    "attribute": "感知+5",
    "condition": "历来实际取得100种不同材料定义",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E05",
    "name": "怪物手札",
    "description": "陌生的面孔，被你留在纸上。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "实际发现20种不同正式怪物模板",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E06",
    "name": "兽行千姿",
    "description": "獠牙之外，生命还有许多模样。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "实际发现50种不同正式怪物模板",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E07",
    "name": "兵器谱",
    "description": "各有锋芒，也各有自己的重量。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "历来实际取得5种不同武器子类型",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E08",
    "name": "五衣百态",
    "description": "不同的衣甲，讲着不同的生存之道。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "历来实际取得五种甲类各至少一件合法装备",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E09",
    "name": "优秀之物",
    "description": "寻常光里，忽然多出一分明亮。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "首次正常取得优秀稀有度物品",
    "scope": "场",
    "dependency": "现",
    "category": "收藏"
  },
  {
    "id": "ACH_E10",
    "name": "精良之物",
    "description": "精心打磨过的东西，会自己发出回声。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "首次正常取得精良稀有度物品",
    "scope": "场",
    "dependency": "现",
    "category": "收藏"
  },
  {
    "id": "ACH_E11",
    "name": "稀有之物",
    "description": "稀少的光芒，曾在你的掌中停留。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "首次正常取得稀有稀有度物品",
    "scope": "场",
    "dependency": "现",
    "category": "收藏"
  },
  {
    "id": "ACH_E12",
    "name": "一段史诗",
    "description": "器物沉默着，岁月却在其中喧响。",
    "rarity": "稀有",
    "attribute": "精神+5",
    "condition": "首次正常取得史诗稀有度装备实例",
    "scope": "场",
    "dependency": "现",
    "category": "收藏"
  },
  {
    "id": "ACH_E13",
    "name": "遗落的神光",
    "description": "某道被遗落的光，重新认出了人间。",
    "rarity": "传说",
    "attribute": "感知+8",
    "condition": "首次通过正式获取入口取得神器，排除管理发放",
    "scope": "场",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E14",
    "name": "草木有名",
    "description": "叶与根，都有自己未说完的名字。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "实际取得5种带植物材料标签的不同定义",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E15",
    "name": "山石有骨",
    "description": "石头的沉默里，藏着不肯熄灭的骨。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "实际取得5种锻材定义",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E16",
    "name": "炼材小集",
    "description": "混沌的材料，也有可辨认的性情。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "实际取得5种炼材定义",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E17",
    "name": "三域之心",
    "description": "每一片土地，都留下了不同的心跳。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "实际取得3种不同区域锻材定义",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E18",
    "name": "九色尘埃",
    "description": "微尘聚在掌心，像一场很小的星雨。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "实际取得当前九种元素微尘各至少1份",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E19",
    "name": "微光未散",
    "description": "消散之物，仍有不愿熄灭的余光。",
    "rarity": "精良",
    "attribute": "感知+3",
    "condition": "实际取得血肉残渣、能量余烬、魔力微弧各至少1份",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E20",
    "name": "装备备忘",
    "description": "曾披在身上的重量，都有一页记录。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "本世实际装备过10种不同装备定义",
    "scope": "世",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E21",
    "name": "药瓶小柜",
    "description": "瓶中春水，静候生命需要它的时候。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "实际取得5种不同恢复药剂定义",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E22",
    "name": "料理见闻",
    "description": "舌尖记住了路途的另一种颜色。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "实际食用5种不同料理并取得合法效果",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E23",
    "name": "书香十卷",
    "description": "书页叠起，陌生的世界近了一点。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "实际拥有过10种不同书籍/卷宗定义",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E24",
    "name": "自制图录",
    "description": "你留下的形状，渐渐多过空白。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "亲手成功制作10种不同配方定义的作品",
    "scope": "种",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_E25",
    "name": "不止一面",
    "description": "一件器物，陪你走过了自己的故事。",
    "rarity": "精良",
    "attribute": "感知+3",
    "condition": "同一装备实例在本人持有期间完成装备、实际使用与维修",
    "scope": "世",
    "dependency": "扩",
    "category": "收藏"
  },
  {
    "id": "ACH_F01",
    "name": "开口之前",
    "description": "刀锋还未出鞘，声音先走了一步。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "首次在正式PVE开战前进行一次合法交涉",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F02",
    "name": "刀剑未出",
    "description": "安静的结局，也值得被记住。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "首次交涉成功并完成对应结果结算",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F03",
    "name": "五种语言",
    "description": "不同的喉音里，你听见了相同的迟疑。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "与5种不同怪物模板交涉成功",
    "scope": "种",
    "dependency": "扩",
    "category": "交涉"
  },
  {
    "id": "ACH_F04",
    "name": "言有回声",
    "description": "许多紧闭的门，终于有了回声。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "交涉成功20次，按不同生命实例计数",
    "scope": "累",
    "dependency": "扩",
    "category": "交涉"
  },
  {
    "id": "ACH_F05",
    "name": "投其所好",
    "description": "被接住的心意，轻轻改变了距离。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "一次赠礼被正式交涉目标接受并产生正收益",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F06",
    "name": "被拒以后",
    "description": "那一次摇头，没有成为最后的回答。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "礼物被拒但库存未损失，随后同一实例合法交涉成功",
    "scope": "场",
    "dependency": "扩",
    "category": "交涉"
  },
  {
    "id": "ACH_F07",
    "name": "彼此理解",
    "description": "陌生的称呼，开始带上温度。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "同一NPC好感达到正式第二级",
    "scope": "世",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F08",
    "name": "街巷熟面",
    "description": "街巷深处，已有不止一盏为你留的灯。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "本世与3名不同NPC达到正式第二级好感",
    "scope": "世",
    "dependency": "扩",
    "category": "交涉"
  },
  {
    "id": "ACH_F09",
    "name": "人情往来",
    "description": "你经过的人间，渐渐认得你的脚步。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "与10名不同NPC完成非重复的有效互动或委托",
    "scope": "种",
    "dependency": "扩",
    "category": "交涉"
  },
  {
    "id": "ACH_F10",
    "name": "晴日一谈",
    "description": "甜香之外，一段寻常话也值得留下。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "与晴儿完成一次正式剧情或正收益互动",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F11",
    "name": "铁砧旁边",
    "description": "锤声歇下时，人情仍有温度。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "与漠北完成一次正式剧情或正收益互动",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F12",
    "name": "回路之间",
    "description": "齿轮之间，也容得下一次闲谈。",
    "rarity": "普通",
    "attribute": "智力+1",
    "condition": "与唯薇安完成一次正式剧情或正收益互动",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F13",
    "name": "书页微响",
    "description": "书页很轻，相逢并不轻。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "与百味书屋店主完成一次正式剧情或合法服务",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F14",
    "name": "公会识人",
    "description": "来往的人那么多，你的名字没有被略过。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "与莫妮卡完成一次正式委托或剧情交接",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F15",
    "name": "根冠问候",
    "description": "根须深处，一句问候替你留住了风。",
    "rarity": "普通",
    "attribute": "智力+1",
    "condition": "与维萝完成一次正式委托或剧情交接",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F16",
    "name": "风枝来客",
    "description": "云端的纸上，添了一笔人间的暖意。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "与菈芮完成一次正式委托或剧情交接",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F17",
    "name": "温灯记名",
    "description": "雪灯未灭，有人记得你曾来过。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "与温棠完成一次正式委托或剧情交接",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F18",
    "name": "客舍常客",
    "description": "门槛之外是风雪，门槛之内有人应声。",
    "rarity": "普通",
    "attribute": "智力+1",
    "condition": "与格琳达完成一次正式委托或剧情交接",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F19",
    "name": "鲸市账外",
    "description": "账目之外，仍有不能计价的往来。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "与滴算完成一次正式委托或剧情交接",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F20",
    "name": "巡路相逢",
    "description": "路不是空的，总有人和你擦肩。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "首次在合法巡逻地点完成动态NPC有效互动",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F21",
    "name": "送你一程",
    "description": "你把一段陌生的路，走成了别人的归途。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "完成一次真实旅人护送与终点交接",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F22",
    "name": "带人回家",
    "description": "门重新打开时，有人终于能说回来就好。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "完成一次真实救援转送与终点交接",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F23",
    "name": "不是空口",
    "description": "承诺落在实处，便有了分量。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "完成一次正式NPC委托的真实材料交付",
    "scope": "场",
    "dependency": "现",
    "category": "交涉"
  },
  {
    "id": "ACH_F24",
    "name": "二十件托付",
    "description": "许多细小的托付，垒起了信任的形状。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "完成20次有实际贡献的正式NPC委托",
    "scope": "累",
    "dependency": "扩",
    "category": "交涉"
  },
  {
    "id": "ACH_F25",
    "name": "各有喜好",
    "description": "世界没有同一份答案，人心也是。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "对5名不同NPC各赠送一次被接受且符合喜好的礼物",
    "scope": "种",
    "dependency": "扩",
    "category": "交涉"
  },
  {
    "id": "ACH_G01",
    "name": "一起走吧",
    "description": "脚步相逢，远路便多了一种声音。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "首次正式加入一支队伍",
    "scope": "场",
    "dependency": "现",
    "category": "同行"
  },
  {
    "id": "ACH_G02",
    "name": "并肩首胜",
    "description": "胜利的回声里，不止一个名字。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "首次以有效贡献成员身份取得组队PVE胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G03",
    "name": "十次同路",
    "description": "默契从沉默里，一点点长出形状。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "取得10场有本人有效贡献的组队胜利",
    "scope": "累",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G04",
    "name": "百战同行",
    "description": "漫长的战意，终于有了可以并肩的人。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "取得100场有本人有效贡献的组队胜利",
    "scope": "累",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G05",
    "name": "两人一心",
    "description": "转身时，你知道那个人还在那里。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "与同一身份档案队友共同完成10场合格胜利",
    "scope": "累",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G06",
    "name": "三人一程",
    "description": "不同的影子，在同一片光里站稳。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "至少3名有有效贡献的玩家共同完成一次胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G07",
    "name": "合力越峰",
    "description": "巨影落下，众人的呼吸才重新清晰。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "首次作为有效贡献队员参与组队首领胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G08",
    "name": "不缺一人",
    "description": "归来时，名单上没有空白。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "组队首领胜利结算时所有入场玩家存活且无中途换人",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G09",
    "name": "把后背交给你",
    "description": "你接住的，不只是一道伤口。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "一场组队胜利中本人实际治疗或护盾保护其他玩家至少3次",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G10",
    "name": "前排不退",
    "description": "最先迎风的地方，有人始终没有退开。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "一场胜利中承受敌方至少3次有效行动且本人存活",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G11",
    "name": "手把手",
    "description": "前行的人回过头，路便不再那么陡。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "与较本人低至少3级的队友各有实际贡献并完成同级于低级者的正式PVE",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G12",
    "name": "协力调查",
    "description": "一双手看不见的地方，另一双手找到了光。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "两名以上玩家在同一正式动态场景各完成不同有效贡献",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G13",
    "name": "相识于旅途",
    "description": "陌生的名字，从此有了可以抵达的方向。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "首次双方确认好友关系",
    "scope": "场",
    "dependency": "现",
    "category": "同行"
  },
  {
    "id": "ACH_G14",
    "name": "好友三两",
    "description": "人海很远，身边的声音却近了。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "本世同时拥有3名双方确认的好友",
    "scope": "世",
    "dependency": "现",
    "category": "同行"
  },
  {
    "id": "ACH_G15",
    "name": "久别有信",
    "description": "日子隔开距离，没有隔断回声。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "与同一好友在5个不同自然日完成有效互动",
    "scope": "累",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G16",
    "name": "心意送达",
    "description": "礼物不大，来处却让它有了重量。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "首次通过正式赠礼流程向好友成功赠送物品",
    "scope": "场",
    "dependency": "现",
    "category": "同行"
  },
  {
    "id": "ACH_G17",
    "name": "誓约已立",
    "description": "说出口的话，终于有了彼此的回响。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "完成一次双方确认的正式誓约仪式",
    "scope": "场",
    "dependency": "现",
    "category": "同行"
  },
  {
    "id": "ACH_G18",
    "name": "共记一页",
    "description": "记忆被轻轻放下，便不再只属于一个人。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "首次成功记录一次正式誓约回忆",
    "scope": "场",
    "dependency": "现",
    "category": "同行"
  },
  {
    "id": "ACH_G19",
    "name": "十页旧事",
    "description": "往事积成书，翻开时仍有温度。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "与同一誓约对象记录10次不同有效回忆事件",
    "scope": "累",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G20",
    "name": "灵契初成",
    "description": "一道陌生的目光，开始与你看向同处。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "首次通过合法招募结果取得一个同伴",
    "scope": "场",
    "dependency": "现",
    "category": "同行"
  },
  {
    "id": "ACH_G21",
    "name": "它也在战斗",
    "description": "它的呼吸，也留在胜利的余音里。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "同伴首次作出有效贡献并随本人赢得正式PVE",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G22",
    "name": "三种相逢",
    "description": "缘分换过模样，仍一一来到身边。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "历来合法招募3种不同同伴模板，不要求同时拥有",
    "scope": "种",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G23",
    "name": "旧友识途",
    "description": "有些陪伴，不需要每次重新说明。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "同一同伴实例与本人共同取得20场有效胜利",
    "scope": "世",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G24",
    "name": "安全交班",
    "description": "手中的旗交出去了，同行的人仍在向前。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "队长合法移交队伍后，原队伍由新队长完成一场有效胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_G25",
    "name": "共同见证",
    "description": "不同的站位，照见了同一个结局。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "同一场景中以发现者、协助者、见证者三种角色组合完成有效结算",
    "scope": "场",
    "dependency": "扩",
    "category": "同行"
  },
  {
    "id": "ACH_H01",
    "name": "第一把收获",
    "description": "指尖沾上泥土，行囊多了一点大地的馈赠。",
    "rarity": "普通",
    "attribute": "智力+1",
    "condition": "首次完成正式采集并取得实际材料",
    "scope": "场",
    "dependency": "现",
    "category": "采炼"
  },
  {
    "id": "ACH_H02",
    "name": "袋中渐满",
    "description": "每一次弯腰，都让土地近了一点。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "完成20次有效采集结算",
    "scope": "累",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H03",
    "name": "熟悉土地",
    "description": "熟悉的风，会把收获的消息带给你。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "完成100次有效采集结算",
    "scope": "累",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H04",
    "name": "草木之友",
    "description": "草木不会说话，却已和你交换过姓名。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "正常采集取得5种不同植物材料",
    "scope": "种",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H05",
    "name": "山中取材",
    "description": "坚硬的山，也把自己的碎片交到你手上。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "正常采集取得5种不同矿石/锻材",
    "scope": "种",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H06",
    "name": "三地收获",
    "description": "不同的土壤，在掌纹里相遇。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "在3个不同合法区域完成实际采集",
    "scope": "种",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H07",
    "name": "带着风险",
    "description": "你带回收获，也带回了曾经承担的险。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "一次已开启且实际承担风险的险采成功",
    "scope": "场",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H08",
    "name": "封存时刻",
    "description": "某一瞬的丰饶，被你妥善留住。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "合法完成一次采集封存及其最终兑现",
    "scope": "场",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H09",
    "name": "种下一粒",
    "description": "一粒沉默，开始向泥土提问。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "首次实际支付种子完成合法种植",
    "scope": "场",
    "dependency": "现",
    "category": "采炼"
  },
  {
    "id": "ACH_H10",
    "name": "等到成熟",
    "description": "等待有了回应，绿意落进掌心。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "首次从本人种植实例收获实际产物",
    "scope": "场",
    "dependency": "现",
    "category": "采炼"
  },
  {
    "id": "ACH_H11",
    "name": "不同的芽",
    "description": "破土的声音，从来不只有一种。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "实际收获3种不同种植配方",
    "scope": "种",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H12",
    "name": "第一炉药",
    "description": "炉盖轻响，你的手艺第一次有了答案。",
    "rarity": "普通",
    "attribute": "智力+1",
    "condition": "首次本人完成一炉普通炼金成功产物",
    "scope": "场",
    "dependency": "现",
    "category": "采炼"
  },
  {
    "id": "ACH_H13",
    "name": "二十炉火",
    "description": "药香来过又散，分寸留在了手里。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "本人普通炼金成功20个实际付费批次",
    "scope": "累",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H14",
    "name": "百炉余香",
    "description": "长久的火候，把生疏炼成了从容。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "本人普通炼金成功100个实际付费批次",
    "scope": "累",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H15",
    "name": "三槽成方",
    "description": "各异的性情，在炉中找到了相处之法。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "在一炉真实炼金中合法使用主材、辅材、催化槽并成功",
    "scope": "场",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H16",
    "name": "疗伤有术",
    "description": "有人尚未受伤，温柔已经准备好了。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "本人炼成一种实际带恢复HP效果的药剂",
    "scope": "场",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H17",
    "name": "魔力回流",
    "description": "干涸之处，也能等到回潮。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "本人炼成一种实际带恢复MP效果的药剂",
    "scope": "场",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H18",
    "name": "不只是回复",
    "description": "瓶中并非只有春水，也藏着锋芒。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "本人炼成一种合法增益或战斗用途炼金制品",
    "scope": "场",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H19",
    "name": "初次大成功",
    "description": "寻常火光里，忽然长出一分惊喜。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "本人正式炼金首次取得大成功结果",
    "scope": "场",
    "dependency": "现",
    "category": "采炼"
  },
  {
    "id": "ACH_H20",
    "name": "灰中再起",
    "description": "灰烬没有吞掉你下一次点火的心。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "同一配方失败后本人重新付费成功，取消与断线不算失败",
    "scope": "世",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H21",
    "name": "手记第一行",
    "description": "这一次真实的火，被你留在了纸上。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "首次保存一条本人真实炼金记录",
    "scope": "场",
    "dependency": "现",
    "category": "采炼"
  },
  {
    "id": "ACH_H22",
    "name": "不同的配伍",
    "description": "同一口炉，也能听见不同的回答。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "成功完成10种不同合法炼金配方签名",
    "scope": "种",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H23",
    "name": "再现旧方",
    "description": "旧日的香气，沿着记忆重新升起。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "从本人手记重载配方并真实成功制作",
    "scope": "场",
    "dependency": "现",
    "category": "采炼"
  },
  {
    "id": "ACH_H24",
    "name": "先加工再入炉",
    "description": "材料换了一种模样，仍认得你的手。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "将本人实际加工产物投入合法炼金并成功",
    "scope": "场",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_H25",
    "name": "药到实处",
    "description": "炉边的心意，终于抵达需要它的人。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "本人制作的恢复药经正式使用，实际回复本人或允许的受益者",
    "scope": "场",
    "dependency": "扩",
    "category": "采炼"
  },
  {
    "id": "ACH_I01",
    "name": "第一声锤响",
    "description": "锤声落下，原料有了新的命运。",
    "rarity": "普通",
    "attribute": "力量+1",
    "condition": "本人首次正式锻造成功",
    "scope": "场",
    "dependency": "现",
    "category": "锻造"
  },
  {
    "id": "ACH_I02",
    "name": "十锻成器",
    "description": "手中的分寸，渐渐比火光更稳。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "本人成功锻造10个实际批次",
    "scope": "累",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I03",
    "name": "百锻成章",
    "description": "长久的锤声里，浮躁一层层退去。",
    "rarity": "精良",
    "attribute": "感知+3",
    "condition": "本人成功锻造100个实际批次",
    "scope": "累",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I04",
    "name": "刃由我铸",
    "description": "锋芒出自你的手，也记着你的温度。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "本人首次制成武器实例",
    "scope": "场",
    "dependency": "现",
    "category": "锻造"
  },
  {
    "id": "ACH_I05",
    "name": "甲由我裁",
    "description": "在危险抵达以前，你先造好一处庇护。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "本人首次制成防具实例",
    "scope": "场",
    "dependency": "现",
    "category": "锻造"
  },
  {
    "id": "ACH_I06",
    "name": "五部皆备",
    "description": "风掠过周身，每一处都有自己的回应。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "本世同时装备五个防具部位的合法装备",
    "scope": "世",
    "dependency": "现",
    "category": "锻造"
  },
  {
    "id": "ACH_I07",
    "name": "同袍三件",
    "description": "相近的纹理，开始彼此呼应。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "本世实际激活一次三件甲类套装档",
    "scope": "场",
    "dependency": "现",
    "category": "锻造"
  },
  {
    "id": "ACH_I08",
    "name": "五衣成套",
    "description": "零散的重量，终于连成完整的守护。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "本世实际激活一次五件甲类套装档",
    "scope": "场",
    "dependency": "现",
    "category": "锻造"
  },
  {
    "id": "ACH_I09",
    "name": "重甲之路",
    "description": "沉重不是迟疑，是站稳之后的答案。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "穿合法重甲配置完成一场有贡献的正式胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I10",
    "name": "板甲之路",
    "description": "你把坚定，穿成了迎风的形状。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "穿合法板甲配置完成一场有贡献的正式胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I11",
    "name": "轻甲之路",
    "description": "风经过衣甲时，没有带走你的从容。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "穿合法轻甲配置完成一场有贡献的正式胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I12",
    "name": "皮甲之路",
    "description": "柔韧的边缘，留住了进退之间的余地。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "穿合法皮甲配置完成一场有贡献的正式胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I13",
    "name": "布甲之路",
    "description": "轻薄的织物里，也藏着不肯退让的意志。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "穿合法布甲配置完成一场有贡献的正式胜利",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I14",
    "name": "旧器新光",
    "description": "旧日的裂纹，没有成为器物最后的名字。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "首次实际支付材料或费用完成正值耐久维修",
    "scope": "场",
    "dependency": "现",
    "category": "锻造"
  },
  {
    "id": "ACH_I15",
    "name": "伴我百战",
    "description": "它认得你的手，你记得它每一道旧伤。",
    "rarity": "稀有",
    "attribute": "感知+5",
    "condition": "同一武器实例随本人取得100场有效PVE胜利",
    "scope": "世",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I16",
    "name": "再淬一层",
    "description": "火再经过一遍，锋芒便沉稳一分。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "本人首次合法完成装备精炼成功",
    "scope": "场",
    "dependency": "现",
    "category": "锻造"
  },
  {
    "id": "ACH_I17",
    "name": "熔铸留痕",
    "description": "相逢的旧物，在炉里有了共同的将来。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "本人首次完成一笔合法装备熔铸",
    "scope": "场",
    "dependency": "现",
    "category": "锻造"
  },
  {
    "id": "ACH_I18",
    "name": "双材相合",
    "description": "不同的骨性，也能铸成同一道锋。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "在一次正式装备制作中实际消耗两种不同锻材并成功",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I19",
    "name": "星铁入炉",
    "description": "陨落的星，在你的炉中重新发热。",
    "rarity": "精良",
    "attribute": "力量+3",
    "condition": "本人制作成功并实际消耗陨铁锻锭",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I20",
    "name": "地域铭记",
    "description": "一件器物，仍保留着故土的声音。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "本人制品实际包含一项合格区域锻材投入",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I21",
    "name": "不是摆设",
    "description": "亲手留下的锋芒，终于回答了真实的战场。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "本人制成的武器亲自装备后在正式PVE造成实际伤害",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I22",
    "name": "物尽其用",
    "description": "结束也可以成为另一件事的开端。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "首次依法拆解本人持有的合格装备并取得真实材料",
    "scope": "场",
    "dependency": "现",
    "category": "锻造"
  },
  {
    "id": "ACH_I23",
    "name": "回炉有据",
    "description": "旧物留下的余温，照亮了一次新的塑形。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "本人拆解所得材料用于新的合法成功制作",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I24",
    "name": "一器一名",
    "description": "来处、用处、归处，在它身上连成一线。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "同一合法装备实例拥有制作者、投入与正式使用三类可追溯记录",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_I25",
    "name": "匠心留赠",
    "description": "你打造的重量，成了另一个人的依靠。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "本人制成的非绑定合法装备通过正式交易交给另一身份档案",
    "scope": "场",
    "dependency": "扩",
    "category": "锻造"
  },
  {
    "id": "ACH_J01",
    "name": "齿轮初鸣",
    "description": "一枚小小的齿轮，咬住了将来的可能。",
    "rarity": "普通",
    "attribute": "智力+1",
    "condition": "首次正常取得魔力齿轮",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J02",
    "name": "素体在手",
    "description": "空着的躯壳，等待一个愿意开始的人。",
    "rarity": "普通",
    "attribute": "感知+1",
    "condition": "首次正常取得灵枢素体构件",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J03",
    "name": "中枢有光",
    "description": "核心亮起以前，你已看见其中的方向。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "首次正常取得能量中枢基材",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J04",
    "name": "亲手组装",
    "description": "零散的构件，第一次用同一种节奏呼吸。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "本人首次完成正式机巧装配并生成唯一实例",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J05",
    "name": "它认得你",
    "description": "它转过身时，目光停在了你这里。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "首次合法完成机巧认主",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J06",
    "name": "第一口原液",
    "description": "新的养分，让沉默的金属也有了变化。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "首次向本人机巧投入合法育成原液且实际生效",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J07",
    "name": "五味育成",
    "description": "不同的滋养，慢慢写进同一副身躯。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "对同一机巧实例成功使用5种不同合格育成原液",
    "scope": "世",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J08",
    "name": "十二味谱",
    "description": "看似相近的液滴，各自留下不同的回声。",
    "rarity": "稀有",
    "attribute": "感知+5",
    "condition": "历来实际使用十二种已有育成原液各至少一次",
    "scope": "种",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J09",
    "name": "又长大了",
    "description": "昨日的尺度，已经装不下今天的它。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "本人机巧首次正常提升一级",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J10",
    "name": "并肩的齿轮",
    "description": "齿轮的声音，与心跳站在了同一边。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "机巧首次实际参与本人正式胜利并产生贡献",
    "scope": "场",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J11",
    "name": "二十场默契",
    "description": "许多次归来，变成了无需解释的默契。",
    "rarity": "精良",
    "attribute": "感知+3",
    "condition": "同一机巧实例与本人完成20场有贡献的胜利",
    "scope": "世",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J12",
    "name": "整装再出发",
    "description": "尘土被拭去，它又望向了门外。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "首次完成本人机巧真实正值维修或能量补充",
    "scope": "场",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J13",
    "name": "它的打法",
    "description": "命令落到行动里，才真正有了意义。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "修改合法战斗策略后，该机巧在正式战斗中实际执行一次该策略",
    "scope": "场",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J14",
    "name": "学会新招",
    "description": "熟悉的身影，忽然使出陌生的一招。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "同一机巧通过正常成长首次新增可用技能",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J15",
    "name": "不只是一件货物",
    "description": "被留下的记忆，比金属更难替换。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "本人机巧产生首条合格长期记忆事件",
    "scope": "场",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J16",
    "name": "翻开书页",
    "description": "书页翻开时，远方并没有发出声音。",
    "rarity": "普通",
    "attribute": "智力+1",
    "condition": "首次在书屋完成一笔合法购书",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J17",
    "name": "学以致用",
    "description": "纸上的光，终于照到了纸外。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "合法读技能书学会技能，随后在实际玩法中有效使用",
    "scope": "世",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J18",
    "name": "三卷各异",
    "description": "不同的墨迹，在你的理解里彼此相逢。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "实际学习3本不同技能书定义且均成功生效",
    "scope": "种",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J19",
    "name": "书归有价",
    "description": "一本书的旅程，可以从另一双手继续。",
    "rarity": "普通",
    "attribute": "智力+1",
    "condition": "首次通过书屋完成一笔合法出售书卷",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J20",
    "name": "拆开看一看",
    "description": "表象裂开一角，细小的光从里面流出。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "本人首次完成解构并取得实际粒子",
    "scope": "场",
    "dependency": "现",
    "category": "机巧"
  },
  {
    "id": "ACH_J21",
    "name": "微尘成簇",
    "description": "微尘各有颜色，也各有未尽的可能。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "本人解构取得3种不同元素粒子",
    "scope": "种",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J22",
    "name": "五材识微",
    "description": "不同材料的沉默，被你一一听见。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "本人解构5种不同材料定义",
    "scope": "种",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J23",
    "name": "理解后重组",
    "description": "散开的东西，仍能组成新的回答。",
    "rarity": "优秀",
    "attribute": "感知+2",
    "condition": "正常解构所得粒子用于一笔合格机巧/炼金制作",
    "scope": "场",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J24",
    "name": "纸上不是全部",
    "description": "同一句旧话，走到世间便有了不同的回声。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "学会书中技能后完成3种不同合法有效使用场景",
    "scope": "种",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_J25",
    "name": "知识有人用",
    "description": "知识越过你的手，仍在另一个人身上发光。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "本人合法制作的书卷/技能载体由另一身份档案实际学会",
    "scope": "场",
    "dependency": "扩",
    "category": "机巧"
  },
  {
    "id": "ACH_K01",
    "name": "第一笔买卖",
    "description": "钱币轻响，人间的往来由此开始。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "首次完成正式NPC商店购买并实际支付",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K02",
    "name": "卖出所得",
    "description": "行囊里的故事，换来了一点前行的盘缠。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "首次向NPC合法卖出本人正常取得的物品",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K03",
    "name": "集市开张",
    "description": "小小的摊位，也向世界开了一扇门。",
    "rarity": "普通",
    "attribute": "敏捷+1",
    "condition": "首次发布有实物托管的合法市场订单",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K04",
    "name": "银货两讫",
    "description": "各自放下所需，各自带走所愿。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "首次与另一身份档案完成真实市场成交",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K05",
    "name": "十位来客",
    "description": "不同的脚步，都曾在你这里停留。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "与10个不同身份档案完成真实市场交易",
    "scope": "种",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_K06",
    "name": "物归其主",
    "description": "器物换了归处，来历没有随之消失。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "首次成功购入一个合法实例市场商品",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K07",
    "name": "撤单无误",
    "description": "收回尚未启程的东西，也是一种妥当。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "正常撤销本人未成交托管单，实际取回剩余资产",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K08",
    "name": "花在刀刃上",
    "description": "每一枚花出去的钱，都应有值得的去处。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "本世正常商店或市场实付累计10000铜币，退款部分扣回",
    "scope": "世",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_K09",
    "name": "劳有所得",
    "description": "掌心的重量，来自走过的真实路途。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "本世正式任务与正常卖货净收入累计10000铜币，排除赠送和管理邮件",
    "scope": "世",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_K10",
    "name": "一处落脚",
    "description": "远方很多，你终于有一处可以回来。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "首次合法购买家园",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K11",
    "name": "家中有我",
    "description": "门掩上以后，风声留在了外面。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "首次进入本人家园并完成一次有效休息结算",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K12",
    "name": "给家起名",
    "description": "一个名字，让四壁之间有了归属。",
    "rarity": "普通",
    "attribute": "敏捷+1",
    "condition": "首次成功保存合法家园名称",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K13",
    "name": "添一件家具",
    "description": "空荡的角落，开始有了生活的模样。",
    "rarity": "普通",
    "attribute": "体质+1",
    "condition": "首次实际购置并摆放一件合法家具",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K14",
    "name": "五件小幸福",
    "description": "琐碎的喜爱，慢慢拼出家的形状。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "本世家园实际摆放5种不同家具定义",
    "scope": "世",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_K15",
    "name": "留客一席",
    "description": "屋里多一把声音，灯就显得更暖。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "首次按合法访问权限接待一名其他玩家入内",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K16",
    "name": "串门有礼",
    "description": "别人的屋檐下，也曾为你留过一席。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "在3名不同身份档案的授权家园完成有效拜访",
    "scope": "种",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_K17",
    "name": "好好吃饭",
    "description": "热气升起时，疲惫也轻了一点。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "首次实际食用一份料理并生效",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K18",
    "name": "公会一餐",
    "description": "来往的人间，总留着一口热饭。",
    "rarity": "普通",
    "attribute": "敏捷+1",
    "condition": "首次通过公会餐厅完成一次合法用餐",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K19",
    "name": "餐桌新味",
    "description": "舌尖认识的世界，又多了几种颜色。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "通过公会餐厅实际食用3种不同料理",
    "scope": "种",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_K20",
    "name": "信已收到",
    "description": "远来的心意，终于抵达你的手中。",
    "rarity": "普通",
    "attribute": "精神+1",
    "condition": "首次合法领取一封正式系统任务邮件的附件，排除管理员邮件",
    "scope": "场",
    "dependency": "现",
    "category": "日常"
  },
  {
    "id": "ACH_K21",
    "name": "行前备药",
    "description": "你替尚未抵达的险境，留了一点余地。",
    "rarity": "普通",
    "attribute": "敏捷+1",
    "condition": "一次正式出战快照中持有本人合法取得的HP与MP恢复药各至少一份",
    "scope": "场",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_K22",
    "name": "轻装上路",
    "description": "卸下一些重量，才能听清脚下的风。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "因真实新增物品超重后，通过合法整理恢复正常负重并完成一次移动",
    "scope": "世",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_K23",
    "name": "修好再走",
    "description": "收拾好旧日的裂痕，再把脚步交给远方。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "一次正式旅行前完成合法装备维修且随后抵达另一地区",
    "scope": "世",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_K24",
    "name": "办妥再归",
    "description": "出门时牵挂的事，归来时已有了着落。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "同一外出行程完成任务交付、合法服务与真实返家",
    "scope": "世",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_K25",
    "name": "有序的一天",
    "description": "忙与静各得其所，日子便不再匆忙。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "同一自然日完成正式任务、制作或采集、有效休息三种活动",
    "scope": "场",
    "dependency": "扩",
    "category": "日常"
  },
  {
    "id": "ACH_L01",
    "name": "私人的第一封信",
    "description": "一封信，把私人的来路交到了你手上。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "完成本世灯火私人篇的最终结算节点",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L02",
    "name": "一地灯火",
    "description": "熟悉的街巷，开始有了值得守住的灯。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "完成本世灯火地方篇的最终结算节点",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L03",
    "name": "来路相接",
    "description": "不同方向的脚步，终于听见彼此。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "完成本世灯火汇流篇的最终结算节点",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L04",
    "name": "世界仍有回声",
    "description": "世界很大，回应却没有缺席。",
    "rarity": "传说",
    "attribute": "感知+8",
    "condition": "完成本世当前开放灯火世界篇终章",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L05",
    "name": "王都来客",
    "description": "高墙之外的声音，终于有了一席之地。",
    "rarity": "优秀",
    "attribute": "体质+2",
    "condition": "完成王都·外使行馆的对应正式主线交接",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L06",
    "name": "雪灯照归程",
    "description": "归路上的灯，比风雪更有耐心。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "完成北境·雪灯接应站的对应正式主线交接",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L07",
    "name": "云上修理",
    "description": "云很高，修补它的人仍站在人间。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "完成天穹修理院·转乘空港的对应正式主线交接",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L08",
    "name": "公议之席",
    "description": "厚重的门打开后，沉默也获得了位置。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "完成魔界·公议行馆的对应正式主线交接",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L09",
    "name": "生者入天门",
    "description": "你带去地面的尘土，也带去活人的问题。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "完成神界·公务接引厅的对应正式主线交接",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L10",
    "name": "第十三间房",
    "description": "多出来的房间，终于等到了能够归来的人。",
    "rarity": "精良",
    "attribute": "感知+3",
    "condition": "完成失落矿城·第十三间客房的对应正式主线交接",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L11",
    "name": "六地同信",
    "description": "信从各处而来，灯向同一个方向亮起。",
    "rarity": "稀有",
    "attribute": "体质+5",
    "condition": "完成大陆联合接应营地的对应正式主线交接",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L12",
    "name": "界路有归途",
    "description": "路伸向远处，也为归来留下一端。",
    "rarity": "稀有",
    "attribute": "敏捷+5",
    "condition": "完成界路中枢·联合前哨的对应正式主线交接",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L13",
    "name": "矿城的门",
    "description": "石门后的黑暗，第一次向你让开。",
    "rarity": "优秀",
    "attribute": "精神+2",
    "condition": "首次通过地下迷宫一个正式可结算关卡",
    "scope": "场",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L14",
    "name": "迷宫归人",
    "description": "迷宫没有变短，你已记得归途。",
    "rarity": "稀有",
    "attribute": "力量+5",
    "condition": "首次完成当前地下迷宫一次完整正式通关",
    "scope": "场",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L15",
    "name": "通缉之外的功劳",
    "description": "一张薄纸上的托付，被你带回了答案。",
    "rarity": "优秀",
    "attribute": "智力+2",
    "condition": "首次完成正式PVE悬赏交付，排除玩家追杀奖励",
    "scope": "场",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L16",
    "name": "二十张委托单",
    "description": "留下的签收，渐渐厚过最初的迟疑。",
    "rarity": "精良",
    "attribute": "感知+3",
    "condition": "完成20次不同正式PVE悬赏事件",
    "scope": "累",
    "dependency": "扩",
    "category": "剧情"
  },
  {
    "id": "ACH_L17",
    "name": "四店藏门",
    "description": "寻常店门之后，另有一段未说尽的路。",
    "rarity": "稀有",
    "attribute": "体质+5",
    "condition": "本世正式完成任一现有四店隐藏二转任务链",
    "scope": "世",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L18",
    "name": "切磋有度",
    "description": "锋芒相逢，也可以点到为止。",
    "rarity": "优秀",
    "attribute": "敏捷+2",
    "condition": "首次在正式NPC切磋中满足获胜条件",
    "scope": "场",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L19",
    "name": "三位对手",
    "description": "不同的对手，让你看见不同的自己。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "合法击败3名不同NPC切磋对手",
    "scope": "种",
    "dependency": "扩",
    "category": "剧情"
  },
  {
    "id": "ACH_L20",
    "name": "留下性命",
    "description": "刀锋停住以后，故事仍有余地。",
    "rarity": "优秀",
    "attribute": "力量+2",
    "condition": "用I10现有降服机制完成一次正式降服结算",
    "scope": "场",
    "dependency": "现",
    "category": "剧情"
  },
  {
    "id": "ACH_L21",
    "name": "丹中见路",
    "description": "炉中起落的微光，终于照见你自己的路。",
    "rarity": "精良",
    "attribute": "智力+3",
    "condition": "在已开放仙路上完成炼丹支线D03并正式入门",
    "scope": "世",
    "dependency": "新",
    "category": "剧情"
  },
  {
    "id": "ACH_L22",
    "name": "器中见我",
    "description": "器物记住了你的气，也记住你的手。",
    "rarity": "精良",
    "attribute": "感知+3",
    "condition": "在已开放仙路上完成炼器支线R03并正式入门",
    "scope": "世",
    "dependency": "新",
    "category": "剧情"
  },
  {
    "id": "ACH_L23",
    "name": "阵外有路",
    "description": "你给世界留下缺口，世界便还你一条路。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "在已开放仙路上完成阵法支线A03并正式入门",
    "scope": "世",
    "dependency": "新",
    "category": "剧情"
  },
  {
    "id": "ACH_L24",
    "name": "纸上留息",
    "description": "一息落在纸上，竟比墨迹更长久。",
    "rarity": "精良",
    "attribute": "敏捷+3",
    "condition": "在已开放仙路上完成符箓支线F03并正式入门",
    "scope": "世",
    "dependency": "新",
    "category": "剧情"
  },
  {
    "id": "ACH_L25",
    "name": "木中回声",
    "description": "木与金属之间，多了一声属于你的回应。",
    "rarity": "精良",
    "attribute": "精神+3",
    "condition": "在已开放仙路上完成傀儡支线P03并正式入门",
    "scope": "世",
    "dependency": "新",
    "category": "剧情"
  }
];
export const achievementDefinitions = [...baseAchievementDefinitions.filter(d=>!retiredAchievementIdSet.has(d.id)),...pvpAchievementDefinitions,...easterAchievementDefinitions,...challengeAchievementDefinitions,...surpriseAchievementDefinitions];
export type AchievementDefinition = typeof achievementDefinitions[number];
