export const surpriseAchievementDefinitions = [
  {
    "id": "ACH_EGG17",
    "name": "蓝条辞职，血条留任",
    "description": "一边坚持全勤，另一边已经递了辞呈。",
    "rarity": "稀有",
    "attribute": "智力+5",
    "condition": "独自有效击败至少同级正式Boss；结算时HP满、MP为0。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG18",
    "name": "命是借来的",
    "description": "账房数了十遍，仍觉得你不该站在这里。",
    "rarity": "稀有",
    "attribute": "体质+5",
    "condition": "独自有效击败至少同级正式Boss并存活，该场累计实际损失HP至少为本人最大HP的10倍。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG19",
    "name": "缝完这座山",
    "description": "你没有挥剑，只把整支队伍从裂缝里一针针拉回来。",
    "rarity": "传说",
    "attribute": "精神+8",
    "condition": "组队击败至少同级正式Boss；本人实际伤害为0，对其他队员的实际治疗累计至少为本人最大HP的20倍。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG20",
    "name": "最后一张站票",
    "description": "回程的车来了，只有你还需要扶手。",
    "rarity": "稀有",
    "attribute": "敏捷+5",
    "condition": "至少3名玩家全部有有效贡献的正式Boss胜利；无NPC队友，结算时只有本人存活，Boss不低于全队最高等级。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG21",
    "name": "全队进入省电模式",
    "description": "胜利已经亮了，蓝条就不必再亮。",
    "rarity": "传说",
    "attribute": "智力+8",
    "condition": "至少3名玩家且无NPC队友，全员有效贡献并存活，击败不低于全队最高等级的正式Boss；所有玩家结算MP为0。符合者共同达成。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG22",
    "name": "染坊拒绝加班",
    "description": "它身上的颜色还没干，你身上的绷带已经不够用了。",
    "rarity": "史诗",
    "attribute": "感知+12",
    "condition": "独自有效击败至少同级正式Boss；本人造成至少6种非无元素伤害，承受至少30次有效敌方命中且存活。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG23",
    "name": "余额不足，胜利到账",
    "description": "账上什么都没有，偏偏多了一场胜利。",
    "rarity": "传说",
    "attribute": "精神+8",
    "condition": "独自有效击败至少同级正式Boss，恰好剩1HP、0MP。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG24",
    "name": "留着蓝条过年",
    "description": "它打到怀疑人生，你还舍不得动那一格蓝。",
    "rarity": "稀有",
    "attribute": "力量+5",
    "condition": "独自有效击败至少同级正式Boss并存活；承受至少100次有效敌方命中，结算MP等于正值最大MP。仅描述结算余额，不要求全程未施法。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG25",
    "name": "药房驻场代表",
    "description": "前线没有你的战绩，所有活人却都记得你。",
    "rarity": "稀有",
    "attribute": "精神+5",
    "condition": "组队有效击败至少同级正式Boss；本人伤害为0，对其他队员治疗至少为本人最大HP的5倍，并实际用技能治疗过HP低于30%的队员。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG26",
    "name": "请把奖杯放床头",
    "description": "胜利的消息到了，你暂时不方便起身签收。",
    "rarity": "精良",
    "attribute": "体质+3",
    "condition": "至少2名玩家组队击败至少同级正式Boss；本人已倒地，该场本人累计有效伤害不低于一个合格Boss最大HP的50%。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG27",
    "name": "每人保管一口气",
    "description": "谁也不敢先说话，怕把最后那一点吹散了。",
    "rarity": "史诗",
    "attribute": "体质+12",
    "condition": "至少3名玩家且无NPC队友，全员有效贡献，击败不低于全队最高等级的正式Boss；每名玩家结算HP恰好为1。符合者共同达成。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG28",
    "name": "战地医院兼营染色",
    "description": "药箱里有绷带，袖口里还有六种天气。",
    "rarity": "史诗",
    "attribute": "智力+12",
    "condition": "组队有效击败至少同级正式Boss；本人造成至少6种非无元素伤害，同时对其他队员实际治疗至少为本人最大HP的5倍。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG29",
    "name": "差一个标点",
    "description": "故事只差一个句号，倒下的却是执笔的人。",
    "rarity": "稀有",
    "attribute": "感知+5",
    "condition": "独自正式Boss战败，Boss至少同级且恰好剩1HP；本人该场伤害至少为Boss最大HP的50%。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG30",
    "name": "彩虹落地了",
    "description": "六种光都没能照亮回去的路。",
    "rarity": "稀有",
    "attribute": "智力+5",
    "condition": "独自败给至少同级正式Boss，本人已归零，该场实际造成至少6种非无元素伤害。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG31",
    "name": "盾牌申请离职",
    "description": "它写满了一百行理由，最后一行是你的名字。",
    "rarity": "稀有",
    "attribute": "力量+5",
    "condition": "独自败给至少同级正式Boss，本人该场承受至少100次有效敌方命中并最终归零。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG32",
    "name": "十条命也不够",
    "description": "命运把借条叠好，说下次先还利息。",
    "rarity": "稀有",
    "attribute": "体质+5",
    "condition": "独自败给至少同级正式Boss，累计实际损失HP至少为本人最大HP的10倍且最终归零。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG33",
    "name": "医嘱是撤退",
    "description": "你治好了所有能治的伤，唯独没治好这场决定。",
    "rarity": "传说",
    "attribute": "精神+8",
    "condition": "至少2名玩家参与的正式Boss战最终战败；本人HP归零，对其他队员实际治疗至少为本人最大HP的20倍，Boss至少与本人同级。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG34",
    "name": "已读，但来不及回复",
    "description": "它的问候很简短，你的回答一直停在输入中。",
    "rarity": "精良",
    "attribute": "敏捷+3",
    "condition": "满足满HP被同级至高2级Boss在第1回合第1次行动单次致死；本人MP仍满且最大MP为正，Boss仍满HP，本人该场未造成伤害，独自战败。",
    "scope": "场",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG35",
    "name": "炉子也有叛逆期",
    "description": "第五次掀屋顶时，你终于承认它不是在通风。",
    "rarity": "稀有",
    "attribute": "体质+5",
    "condition": "个人三槽炼金连续5个实际付费订单均整单失败并判定炸炉；任一已结算非炸炉个人订单打断，取消、代工和重复提交不推进。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG36",
    "name": "这张配方欠我一栋楼",
    "description": "你把五十张修缮单压在下面，终于写出了那个对字。",
    "rarity": "传说",
    "attribute": "智力+8",
    "condition": "同一槽位配方累计50次整单失败炸炉后，再次亲自付费炼出至少一批大成功；顺序颠倒不计。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG37",
    "name": "黑烟也能修家谱",
    "description": "祖传秘方还没找到，祖传黑烟已经有了一百代。",
    "rarity": "传说",
    "attribute": "体质+8",
    "condition": "个人三槽炼金累计100次整单失败且系统判定炸炉；取消、代工、普通失败及重试不计。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG38",
    "name": "偶然已经住下了",
    "description": "它原本只是路过，后来连钥匙都有了。",
    "rarity": "传说",
    "attribute": "智力+8",
    "condition": "个人三槽炼金累计1000个实际付费大成功批次；额外产物不增加次数，代工不计。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG39",
    "name": "配方索引需要索引",
    "description": "你为了找到那本笔记，又写了一本笔记。",
    "rarity": "传说",
    "attribute": "感知+8",
    "condition": "个人三槽炼金成功完成100种不同槽位配方签名；物品编号与槽位顺序去重，改变数量不算新配方。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG40",
    "name": "闭眼也别真闭眼",
    "description": "第一千炉的时候，你终于学会了不说那句肯定没事。",
    "rarity": "稀有",
    "attribute": "精神+5",
    "condition": "同一个三槽配方累计亲自成功1000个实际付费批次；其他配方不能拼数，代工与额外产物不计。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG41",
    "name": "星星有了工号",
    "description": "它曾经负责许愿，现在负责按时进炉。",
    "rarity": "传说",
    "attribute": "力量+8",
    "condition": "累计1000次本人成功装备制作中实际消耗陨铁锻锭；同一批投入多块只计1次，失败和代工不计。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG42",
    "name": "把山川打进铁里",
    "description": "每一声锤响，都带着远方的口音。",
    "rarity": "传说",
    "attribute": "敏捷+8",
    "condition": "累计1000次本人成功装备制作中实际消耗合格区域锻材；同一批投入多种只计1次，失败和代工不计。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG43",
    "name": "三处山头一个熟人",
    "description": "这边说你刚走，那边说你又来了。",
    "rarity": "稀有",
    "attribute": "敏捷+5",
    "condition": "在3个不同正式区域各完成至少100处不同出生实例的有效采集并取得产物；同一资源重复领取不计。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG44",
    "name": "地质学上的老熟人",
    "description": "石头不说话，你却已经听懂了它的沉默。",
    "rarity": "稀有",
    "attribute": "感知+5",
    "condition": "同一种资源物品累计从1000处不同出生实例合法采集取得；其他物品不能拼数，取消和重复领取不计。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG45",
    "name": "刀鞘比刀更忙",
    "description": "第一千次收好兵器时，你发现它已经习惯了和平。",
    "rarity": "传说",
    "attribute": "精神+8",
    "condition": "本人作为操作交涉者，对1000个不同怪物生命实例完成正式和平结算；旁观、失败、重复结算不计。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  },
  {
    "id": "ACH_EGG46",
    "name": "怪物也有通讯录",
    "description": "翻到第二十页时，招呼声已经不像来自敌人。",
    "rarity": "稀有",
    "attribute": "感知+5",
    "condition": "本人作为操作交涉者成功和平结算20种不同怪物模板；同种重复、赠礼未成功、仅对话和旁观不计。",
    "scope": "账",
    "dependency": "现",
    "category": "秘闻"
  }
];
