import type { ResidentSkill } from './resident-skill.config';
/** 三地书店术式：不加入域民领悟池。 */
export type FolioSkill = ResidentSkill & { learnLevel: number; targetCount: number; parts: number[]; shop: string; price: number };
export const folioSkills: readonly FolioSkill[] = [
  {
    "id": "FP01",
    "code": "folio_p01",
    "name": "迅刃斩",
    "tier": "基础",
    "learnLevel": 1,
    "category": "physical",
    "mana": 10,
    "cooldown": 0,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 95,
    "parts": [
      95
    ],
    "description": "纯单体伤害。",
    "damageType": "斩击",
    "ranged": false,
    "shop": "bookshop",
    "price": 150
  },
  {
    "id": "FP02",
    "code": "folio_p02",
    "name": "裂隙追斩",
    "tier": "下位",
    "learnLevel": 6,
    "category": "physical",
    "mana": 36,
    "cooldown": 2,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 135,
    "parts": [
      135
    ],
    "description": "若目标已有普通减防，威力+10%；条件不随强效放大。",
    "damageType": "斩击",
    "ranged": false,
    "shop": "bookshop",
    "price": 400
  },
  {
    "id": "FP03",
    "code": "folio_p03",
    "name": "双弧斩",
    "tier": "下位",
    "learnLevel": 6,
    "category": "physical",
    "mana": 44,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "无",
    "power": 95,
    "parts": [
      95
    ],
    "description": "两个不同目标；不足两人不补斩。",
    "damageType": "斩击",
    "ranged": false,
    "shop": "bookshop",
    "price": 440
  },
  {
    "id": "FP04",
    "code": "folio_p04",
    "name": "三日月连斩",
    "tier": "中位",
    "learnLevel": 25,
    "category": "physical",
    "mana": 80,
    "cooldown": 4,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 3,
    "element": "无",
    "power": 88,
    "parts": [
      88
    ],
    "description": "至多三个不同目标；本次对首目标的命中率修正+10%（补足未命中部分，非最终百分点）。",
    "damageType": "斩击",
    "ranged": false,
    "shop": "bookshop",
    "price": 990
  },
  {
    "id": "FP05",
    "code": "folio_p05",
    "name": "旋刃横扫",
    "tier": "下位",
    "learnLevel": 12,
    "category": "physical",
    "mana": 48,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemies",
    "targetCount": 0,
    "element": "无",
    "power": 75,
    "parts": [
      75
    ],
    "description": "纯全体伤害。",
    "damageType": "斩击",
    "ranged": false,
    "shop": "bookshop",
    "price": 460
  },
  {
    "id": "FP06",
    "code": "folio_p06",
    "name": "落叶剑舞",
    "tier": "中位",
    "learnLevel": 32,
    "category": "physical",
    "mana": 96,
    "cooldown": 5,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "无",
    "power": 125,
    "parts": [
      125
    ],
    "description": "吟唱式蓄势，次回合自动以125%威力攻击敌方全体；不附控制。",
    "damageType": "斩击",
    "ranged": false,
    "shop": "bookshop",
    "price": 1040
  },
  {
    "id": "FP07",
    "code": "folio_p07",
    "name": "裂甲断刃",
    "tier": "中位",
    "learnLevel": 25,
    "category": "physical",
    "mana": 72,
    "cooldown": 4,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 155,
    "parts": [
      155
    ],
    "description": "本次忽略10%有效物防；固定穿透，不吃强效。",
    "damageType": "斩击",
    "ranged": false,
    "shop": "bookshop",
    "price": 900
  },
  {
    "id": "FP08",
    "code": "folio_p08",
    "name": "回旋二连斩",
    "tier": "下位",
    "learnLevel": 6,
    "category": "physical",
    "mana": 40,
    "cooldown": 2,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 130,
    "parts": [
      65,
      65
    ],
    "description": "同一目标两段分别计算防御；附加触发按每次施法限制。",
    "damageType": "斩击",
    "ranged": false,
    "shop": "bookshop",
    "price": 400
  },
  {
    "id": "FP09",
    "code": "folio_p09",
    "name": "迅影突刺",
    "tier": "基础",
    "learnLevel": 1,
    "category": "physical",
    "mana": 10,
    "cooldown": 0,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 95,
    "parts": [
      95
    ],
    "description": "命中后不附控制，纯伤害。",
    "damageType": "刺击",
    "ranged": false,
    "shop": "leaf_skill_shop",
    "price": 150
  },
  {
    "id": "FP10",
    "code": "folio_p10",
    "name": "鹰眼穿刺",
    "tier": "下位",
    "learnLevel": 6,
    "category": "physical",
    "mana": 34,
    "cooldown": 2,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 125,
    "parts": [
      125
    ],
    "description": "本次攻击命中值+10点，参与属性对抗；不直接修正命中率。",
    "damageType": "刺击",
    "ranged": false,
    "shop": "leaf_skill_shop",
    "price": 400
  },
  {
    "id": "FP11",
    "code": "folio_p11",
    "name": "双星突刺",
    "tier": "下位",
    "learnLevel": 6,
    "category": "physical",
    "mana": 44,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "无",
    "power": 95,
    "parts": [
      95
    ],
    "description": "两个不同目标，各自判定命中。",
    "damageType": "刺击",
    "ranged": false,
    "shop": "leaf_skill_shop",
    "price": 440
  },
  {
    "id": "FP12",
    "code": "folio_p12",
    "name": "流星三连刺",
    "tier": "中位",
    "learnLevel": 25,
    "category": "physical",
    "mana": 82,
    "cooldown": 4,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 3,
    "element": "无",
    "power": 90,
    "parts": [
      90
    ],
    "description": "至多三个不同目标，未命中不转移攻击次数。",
    "damageType": "刺击",
    "ranged": false,
    "shop": "leaf_skill_shop",
    "price": 990
  },
  {
    "id": "FP13",
    "code": "folio_p13",
    "name": "散羽穿刺",
    "tier": "下位",
    "learnLevel": 12,
    "category": "physical",
    "mana": 48,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemies",
    "targetCount": 0,
    "element": "无",
    "power": 75,
    "parts": [
      75
    ],
    "description": "纯全体刺击。",
    "damageType": "刺击",
    "ranged": false,
    "shop": "leaf_skill_shop",
    "price": 460
  },
  {
    "id": "FP14",
    "code": "folio_p14",
    "name": "骤雨枪阵",
    "tier": "中位",
    "learnLevel": 32,
    "category": "physical",
    "mana": 96,
    "cooldown": 5,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "无",
    "power": 125,
    "parts": [
      125
    ],
    "description": "预备一回合后以125%威力攻击敌方全体；目标数不随专精增长。",
    "damageType": "刺击",
    "ranged": false,
    "shop": "leaf_skill_shop",
    "price": 1040
  },
  {
    "id": "FP15",
    "code": "folio_p15",
    "name": "钉影穿刺",
    "tier": "中位",
    "learnLevel": 25,
    "category": "physical",
    "mana": 76,
    "cooldown": 4,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 145,
    "parts": [
      145
    ],
    "description": "命中后减速15%，持续2回合；非定身。",
    "damageType": "刺击",
    "ranged": false,
    "shop": "leaf_skill_shop",
    "price": 900
  },
  {
    "id": "FP16",
    "code": "folio_p16",
    "name": "疾风连刺",
    "tier": "下位",
    "learnLevel": 6,
    "category": "physical",
    "mana": 44,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 135,
    "parts": [
      45,
      45,
      45
    ],
    "description": "同一目标三段；适合低防，不附多次控制或回蓝。",
    "damageType": "刺击",
    "ranged": false,
    "shop": "leaf_skill_shop",
    "price": 400
  },
  {
    "id": "FP17",
    "code": "folio_p17",
    "name": "震荡击",
    "tier": "基础",
    "learnLevel": 1,
    "category": "physical",
    "mana": 10,
    "cooldown": 0,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 95,
    "parts": [
      95
    ],
    "description": "纯单体打击。",
    "damageType": "打击",
    "ranged": false,
    "shop": "worldtree_skill_shop",
    "price": 150
  },
  {
    "id": "FP18",
    "code": "folio_p18",
    "name": "巨锤重击",
    "tier": "下位",
    "learnLevel": 6,
    "category": "physical",
    "mana": 38,
    "cooldown": 2,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 140,
    "parts": [
      140
    ],
    "description": "无附加控制。",
    "damageType": "打击",
    "ranged": false,
    "shop": "worldtree_skill_shop",
    "price": 400
  },
  {
    "id": "FP19",
    "code": "folio_p19",
    "name": "双重震击",
    "tier": "下位",
    "learnLevel": 6,
    "category": "physical",
    "mana": 44,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "无",
    "power": 92,
    "parts": [
      92
    ],
    "description": "两个不同目标。",
    "damageType": "打击",
    "ranged": false,
    "shop": "worldtree_skill_shop",
    "price": 440
  },
  {
    "id": "FP20",
    "code": "folio_p20",
    "name": "三重震鸣",
    "tier": "中位",
    "learnLevel": 25,
    "category": "physical",
    "mana": 84,
    "cooldown": 4,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 3,
    "element": "无",
    "power": 82,
    "parts": [
      82
    ],
    "description": "只对主目标施加物攻-8%，2回合。",
    "damageType": "打击",
    "ranged": false,
    "shop": "worldtree_skill_shop",
    "price": 990
  },
  {
    "id": "FP21",
    "code": "folio_p21",
    "name": "地裂冲波",
    "tier": "下位",
    "learnLevel": 12,
    "category": "physical",
    "mana": 50,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemies",
    "targetCount": 0,
    "element": "无",
    "power": 72,
    "parts": [
      72
    ],
    "description": "全体减速8%，1回合；需该目标命中。",
    "damageType": "打击",
    "ranged": false,
    "shop": "worldtree_skill_shop",
    "price": 460
  },
  {
    "id": "FP22",
    "code": "folio_p22",
    "name": "战钟轰鸣",
    "tier": "中位",
    "learnLevel": 32,
    "category": "physical",
    "mana": 96,
    "cooldown": 5,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "无",
    "power": 123,
    "parts": [
      123
    ],
    "description": "吟唱后以123%威力攻击敌方全体，不带眩晕。",
    "damageType": "打击",
    "ranged": false,
    "shop": "worldtree_skill_shop",
    "price": 1040
  },
  {
    "id": "FP23",
    "code": "folio_p23",
    "name": "破垒重击",
    "tier": "中位",
    "learnLevel": 25,
    "category": "physical",
    "mana": 76,
    "cooldown": 4,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 150,
    "parts": [
      150
    ],
    "description": "对护盾造成的消耗×1.3，生命伤害不放大；固定倍率。",
    "damageType": "打击",
    "ranged": false,
    "shop": "worldtree_skill_shop",
    "price": 900
  },
  {
    "id": "FP24",
    "code": "folio_p24",
    "name": "叠浪连击",
    "tier": "下位",
    "learnLevel": 6,
    "category": "physical",
    "mana": 42,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 136,
    "parts": [
      68,
      68
    ],
    "description": "两段独立防御；不提供无限追击。",
    "damageType": "打击",
    "ranged": false,
    "shop": "worldtree_skill_shop",
    "price": 400
  },
  {
    "id": "FM01",
    "code": "folio_m01",
    "name": "火焰箭",
    "tier": "基础",
    "learnLevel": 1,
    "category": "magic",
    "mana": 30,
    "cooldown": 1,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "火",
    "power": 95,
    "parts": [
      95
    ],
    "description": "纯单体火伤。",
    "damageType": "火",
    "ranged": true,
    "shop": "bookshop",
    "price": 150
  },
  {
    "id": "FM02",
    "code": "folio_m02",
    "name": "双生炎弹",
    "tier": "下位",
    "learnLevel": 12,
    "category": "magic",
    "mana": 100,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "火",
    "power": 105,
    "parts": [
      105
    ],
    "description": "两个不同目标，无附效。",
    "damageType": "火",
    "ranged": true,
    "shop": "bookshop",
    "price": 440
  },
  {
    "id": "FM03",
    "code": "folio_m03",
    "name": "绯焰之潮",
    "tier": "中位",
    "learnLevel": 32,
    "category": "magic",
    "mana": 210,
    "cooldown": 5,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "火",
    "power": 120,
    "parts": [
      120
    ],
    "description": "命中者灼烧：每回合目标最大HP2%，2回合；Boss每回合0.5%，且每目标每跳不超过施法者魔攻40%。",
    "damageType": "火",
    "ranged": true,
    "shop": "bookshop",
    "price": 1040
  },
  {
    "id": "FM04",
    "code": "folio_m04",
    "name": "闪电针",
    "tier": "基础",
    "learnLevel": 1,
    "category": "magic",
    "mana": 32,
    "cooldown": 1,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "雷",
    "power": 95,
    "parts": [
      95
    ],
    "description": "本次攻击命中值+10点，参与属性对抗；不直接修正命中率。",
    "damageType": "雷",
    "ranged": true,
    "shop": "bookshop",
    "price": 150
  },
  {
    "id": "FM05",
    "code": "folio_m05",
    "name": "双极雷锁",
    "tier": "下位",
    "learnLevel": 12,
    "category": "magic",
    "mana": 100,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "雷",
    "power": 90,
    "parts": [
      90
    ],
    "description": "命中者速度-8%，2回合。",
    "damageType": "雷",
    "ranged": true,
    "shop": "bookshop",
    "price": 440
  },
  {
    "id": "FM06",
    "code": "folio_m06",
    "name": "交错雷网",
    "tier": "中位",
    "learnLevel": 32,
    "category": "magic",
    "mana": 210,
    "cooldown": 5,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "雷",
    "power": 115,
    "parts": [
      115
    ],
    "description": "命中者命中率修正降低15%（命中概率×0.85，非最终百分点），2回合；不是眩晕。",
    "damageType": "雷",
    "ranged": true,
    "shop": "bookshop",
    "price": 1040
  },
  {
    "id": "FM07",
    "code": "folio_m07",
    "name": "暮影诅咒",
    "tier": "下位",
    "learnLevel": 6,
    "category": "magic",
    "mana": 55,
    "cooldown": 2,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "暗",
    "power": 120,
    "parts": [
      120
    ],
    "description": "命中后目标魔攻-8%，2回合。",
    "damageType": "暗",
    "ranged": true,
    "shop": "bookshop",
    "price": 400
  },
  {
    "id": "FM08",
    "code": "folio_m08",
    "name": "双生蚀影",
    "tier": "下位",
    "learnLevel": 12,
    "category": "magic",
    "mana": 100,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "暗",
    "power": 90,
    "parts": [
      90
    ],
    "description": "命中者物攻-8%，2回合。",
    "damageType": "暗",
    "ranged": true,
    "shop": "bookshop",
    "price": 440
  },
  {
    "id": "FM09",
    "code": "folio_m09",
    "name": "暗幕侵蚀",
    "tier": "中位",
    "learnLevel": 32,
    "category": "magic",
    "mana": 190,
    "cooldown": 4,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "暗",
    "power": 110,
    "parts": [
      110
    ],
    "description": "全体暗伤；仅主目标命中时驱散最多2个普通可驱散增益，不动Boss保护。",
    "damageType": "暗",
    "ranged": true,
    "shop": "bookshop",
    "price": 1040
  },
  {
    "id": "FM10",
    "code": "folio_m10",
    "name": "奥术双矢",
    "tier": "基础",
    "learnLevel": 1,
    "category": "magic",
    "mana": 35,
    "cooldown": 1,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "无",
    "power": 95,
    "parts": [
      48,
      47
    ],
    "description": "同一目标两段无属性奥术伤害，各段独立计算防御；不是每段95。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "bookshop",
    "price": 150
  },
  {
    "id": "FM11",
    "code": "folio_m11",
    "name": "双轨星芒",
    "tier": "下位",
    "learnLevel": 12,
    "category": "magic",
    "mana": 100,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "无",
    "power": 105,
    "parts": [
      105
    ],
    "description": "两个不同目标，无附效。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "bookshop",
    "price": 440
  },
  {
    "id": "FM12",
    "code": "folio_m12",
    "name": "星屑风暴",
    "tier": "中位",
    "learnLevel": 32,
    "category": "magic",
    "mana": 200,
    "cooldown": 5,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "无",
    "power": 135,
    "parts": [
      135
    ],
    "description": "纯奥术群攻，不降低防御、不附强控。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "bookshop",
    "price": 1040
  },
  {
    "id": "FM13",
    "code": "folio_m13",
    "name": "岩枪术",
    "tier": "下位",
    "learnLevel": 6,
    "category": "magic",
    "mana": 52,
    "cooldown": 2,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "土",
    "power": 125,
    "parts": [
      125
    ],
    "description": "纯单体土伤。",
    "damageType": "土",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 400
  },
  {
    "id": "FM14",
    "code": "folio_m14",
    "name": "双峰岩刺",
    "tier": "下位",
    "learnLevel": 12,
    "category": "magic",
    "mana": 100,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "土",
    "power": 100,
    "parts": [
      100
    ],
    "description": "两个不同目标；主目标命中后速度-10%，1回合。",
    "damageType": "土",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 440
  },
  {
    "id": "FM15",
    "code": "folio_m15",
    "name": "碎岩震域",
    "tier": "中位",
    "learnLevel": 32,
    "category": "magic",
    "mana": 200,
    "cooldown": 5,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "土",
    "power": 115,
    "parts": [
      115
    ],
    "description": "命中者速度-15%，2回合。",
    "damageType": "土",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 1040
  },
  {
    "id": "FM16",
    "code": "folio_m16",
    "name": "荆棘之矢",
    "tier": "基础",
    "learnLevel": 1,
    "category": "magic",
    "mana": 30,
    "cooldown": 1,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "木",
    "power": 95,
    "parts": [
      95
    ],
    "description": "纯单体木伤。",
    "damageType": "木",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 150
  },
  {
    "id": "FM17",
    "code": "folio_m17",
    "name": "枯萎双藤",
    "tier": "下位",
    "learnLevel": 12,
    "category": "magic",
    "mana": 90,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "木",
    "power": 92,
    "parts": [
      92
    ],
    "description": "命中者造成治疗降低10%，2回合；不影响回蓝。",
    "damageType": "木",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 440
  },
  {
    "id": "FM18",
    "code": "folio_m18",
    "name": "荆棘之庭",
    "tier": "中位",
    "learnLevel": 32,
    "category": "magic",
    "mana": 180,
    "cooldown": 4,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "木",
    "power": 112,
    "parts": [
      112
    ],
    "description": "命中者物攻-15%，2回合；不禁行动。",
    "damageType": "木",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 1040
  },
  {
    "id": "FM19",
    "code": "folio_m19",
    "name": "晨光箭",
    "tier": "基础",
    "learnLevel": 1,
    "category": "magic",
    "mana": 32,
    "cooldown": 1,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "光",
    "power": 95,
    "parts": [
      95
    ],
    "description": "纯单体光伤，不附净化。",
    "damageType": "光",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 150
  },
  {
    "id": "FM20",
    "code": "folio_m20",
    "name": "双耀光矢",
    "tier": "下位",
    "learnLevel": 12,
    "category": "magic",
    "mana": 100,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "光",
    "power": 100,
    "parts": [
      100
    ],
    "description": "两个不同目标，无附效。",
    "damageType": "光",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 440
  },
  {
    "id": "FM21",
    "code": "folio_m21",
    "name": "昼光洪流",
    "tier": "中位",
    "learnLevel": 32,
    "category": "magic",
    "mana": 200,
    "cooldown": 5,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "光",
    "power": 130,
    "parts": [
      130
    ],
    "description": "纯全体光伤；不额外治疗友方。",
    "damageType": "光",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 1040
  },
  {
    "id": "FM22",
    "code": "folio_m22",
    "name": "风刃术",
    "tier": "基础",
    "learnLevel": 1,
    "category": "magic",
    "mana": 30,
    "cooldown": 1,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "风",
    "power": 95,
    "parts": [
      95
    ],
    "description": "纯单体风伤。",
    "damageType": "风",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 150
  },
  {
    "id": "FM23",
    "code": "folio_m23",
    "name": "双旋风刃",
    "tier": "下位",
    "learnLevel": 12,
    "category": "magic",
    "mana": 90,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "风",
    "power": 95,
    "parts": [
      95
    ],
    "description": "两个不同目标；主目标命中后闪避值-8点，最低0，持续2回合；不直接修正闪避率。",
    "damageType": "风",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 440
  },
  {
    "id": "FM24",
    "code": "folio_m24",
    "name": "乱流风域",
    "tier": "中位",
    "learnLevel": 32,
    "category": "magic",
    "mana": 180,
    "cooldown": 4,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "风",
    "power": 115,
    "parts": [
      115
    ],
    "description": "攻击命中者时，攻击方获得15%命中率修正（补足未命中部分，非最终百分点），2回合。",
    "damageType": "风",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 1040
  },
  {
    "id": "FM25",
    "code": "folio_m25",
    "name": "激流弹",
    "tier": "下位",
    "learnLevel": 6,
    "category": "magic",
    "mana": 50,
    "cooldown": 2,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "水",
    "power": 125,
    "parts": [
      125
    ],
    "description": "纯单体水伤。",
    "damageType": "水",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 400
  },
  {
    "id": "FM26",
    "code": "folio_m26",
    "name": "双生涌浪",
    "tier": "下位",
    "learnLevel": 12,
    "category": "magic",
    "mana": 100,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "水",
    "power": 100,
    "parts": [
      100
    ],
    "description": "两个不同目标，无附效。",
    "damageType": "水",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 440
  },
  {
    "id": "FM27",
    "code": "folio_m27",
    "name": "怒潮奔流",
    "tier": "中位",
    "learnLevel": 32,
    "category": "magic",
    "mana": 200,
    "cooldown": 5,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "水",
    "power": 130,
    "parts": [
      130
    ],
    "description": "纯全体水伤，不附治疗。",
    "damageType": "水",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 1040
  },
  {
    "id": "FM28",
    "code": "folio_m28",
    "name": "寒霜尖刺",
    "tier": "下位",
    "learnLevel": 6,
    "category": "magic",
    "mana": 52,
    "cooldown": 2,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 1,
    "element": "冰",
    "power": 115,
    "parts": [
      115
    ],
    "description": "命中后减速10%，2回合。",
    "damageType": "冰",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 400
  },
  {
    "id": "FM29",
    "code": "folio_m29",
    "name": "双生冰棱",
    "tier": "下位",
    "learnLevel": 12,
    "category": "magic",
    "mana": 100,
    "cooldown": 3,
    "chant": 0,
    "scope": "enemy",
    "targetCount": 2,
    "element": "冰",
    "power": 90,
    "parts": [
      90
    ],
    "description": "命中者减速10%，2回合。",
    "damageType": "冰",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 440
  },
  {
    "id": "FM30",
    "code": "folio_m30",
    "name": "碎冰风暴",
    "tier": "中位",
    "learnLevel": 32,
    "category": "magic",
    "mana": 200,
    "cooldown": 5,
    "chant": 1,
    "scope": "enemies",
    "targetCount": 0,
    "element": "冰",
    "power": 105,
    "parts": [
      105
    ],
    "description": "命中者减速22%，2回合；无冻结。",
    "damageType": "冰",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 1040
  },
  {
    "id": "FS01",
    "code": "folio_s01",
    "name": "净化术",
    "tier": "基础",
    "learnLevel": 1,
    "category": "utility",
    "mana": 45,
    "cooldown": 1,
    "chant": 0,
    "scope": "ally",
    "targetCount": 1,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "清除1个普通可净化负面；无可清除状态时禁止提交，不消耗行动。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "bookshop",
    "price": 150
  },
  {
    "id": "FS02",
    "code": "folio_s02",
    "name": "净愈祷言",
    "tier": "下位",
    "learnLevel": 6,
    "category": "utility",
    "mana": 110,
    "cooldown": 3,
    "chant": 0,
    "scope": "ally",
    "targetCount": 1,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "清除1个普通可净化负面，治疗60%魔攻；无负面仍可治疗。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 400
  },
  {
    "id": "FS03",
    "code": "folio_s03",
    "name": "双生净流",
    "tier": "下位",
    "learnLevel": 12,
    "category": "utility",
    "mana": 140,
    "cooldown": 3,
    "chant": 0,
    "scope": "ally",
    "targetCount": 2,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "两个不同友方各清除1个普通负面；至少一人存在可净化状态。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 440
  },
  {
    "id": "FS04",
    "code": "folio_s04",
    "name": "净愈之歌",
    "tier": "中位",
    "learnLevel": 25,
    "category": "utility",
    "mana": 250,
    "cooldown": 5,
    "chant": 0,
    "scope": "allies",
    "targetCount": 0,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "各清除1个普通负面，并治疗各40%魔攻；移除数量固定。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 1080
  },
  {
    "id": "FS05",
    "code": "folio_s05",
    "name": "净化屏障",
    "tier": "中位",
    "learnLevel": 25,
    "category": "utility",
    "mana": 150,
    "cooldown": 4,
    "chant": 0,
    "scope": "ally",
    "targetCount": 1,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "清除最多2个普通负面，获得12%最大HP护盾3回合；护盾不叠加。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 900
  },
  {
    "id": "FS06",
    "code": "folio_s06",
    "name": "涤伤之潮",
    "tier": "中位",
    "learnLevel": 32,
    "category": "utility",
    "mana": 220,
    "cooldown": 4,
    "chant": 1,
    "scope": "allies",
    "targetCount": 0,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "仅清除每人最多3个中毒/灼烧/流血类普通持续伤害，治疗各75%魔攻。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 1080
  },
  {
    "id": "FS07",
    "code": "folio_s07",
    "name": "战意祝福",
    "tier": "下位",
    "learnLevel": 6,
    "category": "utility",
    "mana": 70,
    "cooldown": 3,
    "chant": 0,
    "scope": "ally",
    "targetCount": 1,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "物攻+18%，3回合。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "bookshop",
    "price": 400
  },
  {
    "id": "FS08",
    "code": "folio_s08",
    "name": "魔力增幅",
    "tier": "下位",
    "learnLevel": 6,
    "category": "utility",
    "mana": 75,
    "cooldown": 3,
    "chant": 0,
    "scope": "ally",
    "targetCount": 1,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "魔攻+18%，3回合。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "bookshop",
    "price": 400
  },
  {
    "id": "FS09",
    "code": "folio_s09",
    "name": "岩肤术",
    "tier": "下位",
    "learnLevel": 6,
    "category": "utility",
    "mana": 75,
    "cooldown": 3,
    "chant": 0,
    "scope": "ally",
    "targetCount": 1,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "物防+25%，3回合。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 400
  },
  {
    "id": "FS10",
    "code": "folio_s10",
    "name": "抗魔结界",
    "tier": "下位",
    "learnLevel": 6,
    "category": "utility",
    "mana": 75,
    "cooldown": 3,
    "chant": 0,
    "scope": "ally",
    "targetCount": 1,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "魔防+25%，3回合。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 400
  },
  {
    "id": "FS11",
    "code": "folio_s11",
    "name": "风行术",
    "tier": "下位",
    "learnLevel": 6,
    "category": "utility",
    "mana": 65,
    "cooldown": 3,
    "chant": 0,
    "scope": "ally",
    "targetCount": 1,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "速度+18%、闪避值+8点，3回合；不直接提高闪避率，不新增行动。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 400
  },
  {
    "id": "FS12",
    "code": "folio_s12",
    "name": "精准祝福",
    "tier": "基础",
    "learnLevel": 1,
    "category": "utility",
    "mana": 25,
    "cooldown": 1,
    "chant": 0,
    "scope": "ally",
    "targetCount": 1,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "下一次直接攻击命中值+10点，触发即消耗，最多保留3回合；不直接修正命中率。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 150
  },
  {
    "id": "FS13",
    "code": "folio_s13",
    "name": "勇气颂歌",
    "tier": "中位",
    "learnLevel": 25,
    "category": "utility",
    "mana": 210,
    "cooldown": 5,
    "chant": 0,
    "scope": "allies",
    "targetCount": 0,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "物攻+12%，3回合。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "bookshop",
    "price": 1080
  },
  {
    "id": "FS14",
    "code": "folio_s14",
    "name": "魔力共鸣",
    "tier": "中位",
    "learnLevel": 25,
    "category": "utility",
    "mana": 220,
    "cooldown": 5,
    "chant": 0,
    "scope": "allies",
    "targetCount": 0,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "魔攻+12%，3回合。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 1080
  },
  {
    "id": "FS15",
    "code": "folio_s15",
    "name": "坚守之阵",
    "tier": "中位",
    "learnLevel": 25,
    "category": "utility",
    "mana": 230,
    "cooldown": 5,
    "chant": 0,
    "scope": "allies",
    "targetCount": 0,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "双防+15%，3回合。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "worldtree_skill_shop",
    "price": 1080
  },
  {
    "id": "FS16",
    "code": "folio_s16",
    "name": "顺风颂歌",
    "tier": "中位",
    "learnLevel": 25,
    "category": "utility",
    "mana": 190,
    "cooldown": 4,
    "chant": 0,
    "scope": "allies",
    "targetCount": 0,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "速度+12%、命中率修正+5%（补足未命中部分，非最终百分点），3回合；不改变本轮已排定行动。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 1080
  },
  {
    "id": "FS17",
    "code": "folio_s17",
    "name": "风之屏障",
    "tier": "中位",
    "learnLevel": 32,
    "category": "utility",
    "mana": 240,
    "cooldown": 5,
    "chant": 1,
    "scope": "allies",
    "targetCount": 0,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "各获得15%最大HP护盾，持续4回合；不额外减伤。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 1080
  },
  {
    "id": "FS18",
    "code": "folio_s18",
    "name": "潮汐再生",
    "tier": "中位",
    "learnLevel": 32,
    "category": "utility",
    "mana": 240,
    "cooldown": 5,
    "chant": 1,
    "scope": "allies",
    "targetCount": 0,
    "element": "无",
    "power": 0,
    "parts": [
      0
    ],
    "description": "再生：每次受益者回合末恢复6%最大HP，共3回合；施放当轮是否触发按其是否尚未行动判断。",
    "damageType": "奥术",
    "ranged": true,
    "shop": "leaf_skill_shop",
    "price": 1080
  }
];
export const folioSkillByCode = (code: string) => folioSkills.find(skill => skill.code === code);
export const folioHasGrowth = (code: string) => new Set('p04 p10 p15 p20 p21 m03 m04 m05 m06 m07 m08 m14 m15 m17 m18 m23 m24 m28 m29 m30 s02 s04 s05 s06 s07 s08 s09 s10 s11 s12 s13 s14 s15 s16 s17 s18'.split(' ').map(id => 'folio_' + id)).has(code);
