import { attributes, type Allocation } from './types';

export type OperationCategory = '成长' | '战斗' | '委托' | '交互' | '探索' | '交易' | '生活';
export type OperationKindRule = {
  title: string; category: OperationCategory; weights: Allocation;
  /** 0.1 积分为一个整数单位；高价值成果建议 30 单位，即 3 点。 */
  rawUnits: number; dailyCapUnits: number; repeatHours: number;
};
const weights = (partial: Partial<Allocation>): Allocation => Object.fromEntries(attributes.map(key => [key, partial[key] ?? 0])) as Allocation;
const rule = (title: string, category: OperationCategory, points: number, partial: Partial<Allocation>, dailyCap = 0, repeatHours = 0): OperationKindRule => ({ title, category, rawUnits: points, dailyCapUnits: dailyCap, repeatHours, weights: weights(partial) });

/** 只有业务结算点能调用这些类型。未登记类型可落 unmapped 事实，但绝不发积分。 */
export const characterOperationKinds: Record<string, OperationKindRule> = {
  'craft.workshop_fusion': rule('熔铸升级', '生活', 0, {strength:1}),
  'craft.workshop_reroll': rule('重铸洗练', '生活', 0, {strength:1}),
  'craft.workshop_refine': rule('装备精炼', '生活', 2, {strength:1,intelligence:1,perception:1},30,1),
  'craft.workshop_breakthrough_failed': rule('精炼突破未成', '生活', 0, {strength:1}),
  'craft.workshop_breakthrough': rule('精炼突破', '生活', 0, {strength:1}),
  'craft.equipment_enchantment': rule('装备附魔', '生活', 0, { intelligence: 1, perception: 1 }),
  'character.created': rule('来到异世界', '成长', 0, { spirit: 1 }),
  'character.name_changed': rule('更改角色姓名', '成长', 0, { spirit: 1, intelligence: 1 }),
  'character.gender_changed': rule('更改角色性别', '成长', 0, { spirit: 1 }),
  'character.adventurer_registered': rule('完成冒险者登记', '成长', 2, { spirit: 1, perception: 1 }, 2),
  'realm.level_up': rule('境界内升级', '成长', 0, { constitution: 1, spirit: 1, strength: 1, intelligence: 1, agility: 1, perception: 1 }),
  'heart.choice': rule('回答窥尘问心', '成长', 0, { spirit: 1, perception: 1 }),
  'heart.deferred': rule('暂缓窥尘问心', '成长', 0, { spirit: 1, perception: 1 }),
  'profession.chosen': rule('选择职业', '成长', 10, { spirit: 1, intelligence: 1 }, 10),
  'profession.blacksmith_quest_accepted': rule('接取锻造师转职委托', '委托', 0, { strength: 1, intelligence: 1 }),
  'profession.blacksmith_quest_completed': rule('备齐锻造师转职材料', '委托', 0, { strength: 1, perception: 1 }),
  'profession.blacksmith_claimed': rule('完成锻造师转职', '成长', 10, { strength: 2, intelligence: 1 }, 10),
  'profession.alchemist_quest_accepted': rule('接取炼金师转职委托', '委托', 0, { intelligence: 1, perception: 1 }),
  'profession.alchemist_quest_completed': rule('备齐炼金师转职材料', '委托', 0, { intelligence: 1, perception: 1 }),
  'profession.alchemist_claimed': rule('完成炼金师转职', '成长', 10, { intelligence: 2, spirit: 1 }, 10),
  'profession.deconstructor_quest_accepted': rule('接取解构师转职委托', '委托', 0, { intelligence: 1, perception: 1 }),
  'profession.deconstructor_quest_completed': rule('备齐解构师转职材料', '委托', 0, { intelligence: 1, perception: 1 }),
  'profession.deconstructor_claimed': rule('完成解构师转职', '成长', 10, { intelligence: 2, perception: 1 }, 10),
  'profession.deconstructor_blueprints_learned': rule('向唯薇安学到异械图纸', '成长', 2, { intelligence: 2, perception: 1 }, 20),
  'bounty.accepted': rule('接取悬赏', '委托', 0, { spirit: 1, perception: 1 }),
  'bounty.abandoned': rule('放弃悬赏', '委托', 0, { spirit: 1, intelligence: 1 }),
  'quest.secondary_abandoned': rule('放弃副职业支线', '委托', 0, { spirit: 1, intelligence: 1 }),
  'bounty.completed': rule('达成悬赏目标', '委托', 30, { strength: 2, perception: 1 }, 90),
  'bounty.claimed': rule('交付悬赏并领取报酬', '委托', 0, { intelligence: 1, spirit: 1 }),
  'market.order_placed': rule('发布市场订单', '交易', 0, { intelligence: 1, perception: 1 }),
  'market.order_cancelled': rule('撤销市场订单', '交易', 0, { intelligence: 1, agility: 1 }),
  'market.order_expired': rule('市场订单到期', '交易', 0, { intelligence: 1, perception: 1 }),
  'market.trade_bought': rule('市场买入成交', '交易', 0, { intelligence: 1, perception: 1 }),
  'market.trade_sold': rule('市场卖出成交', '交易', 0, { intelligence: 1, perception: 1 }),
  'combat.pve.victory': rule('野外战斗胜利', '战斗', 10, { constitution: 1, strength: 1, intelligence: 1 }, 100, 1),
  'combat.pve.defeat': rule('野外战斗落败', '战斗', 0, { constitution: 1, spirit: 1 }),
  'combat.pve.escaped': rule('撤离野外战斗', '战斗', 0, { agility: 1, perception: 1 }),
  'combat.pve.party_victory': rule('队伍战斗胜利', '战斗', 0, { constitution: 1, spirit: 1, strength: 1, intelligence: 1, agility: 1, perception: 1 }),
  'combat.pve.party_defeat': rule('队伍战斗落败', '战斗', 0, { constitution: 1, spirit: 1 }),
  'combat.pve.party_escaped': rule('队伍撤离战斗', '战斗', 0, { agility: 1, perception: 1 }),
  'combat.pvp.victory': rule('玩家对战胜利', '战斗', 10, { strength: 1, agility: 1, perception: 1 }, 30, 24),
  'combat.pvp.defeat': rule('玩家对战落败', '战斗', 0, { constitution: 1, spirit: 1 }),
  'combat.pvp.escaped': rule('撤离玩家对战', '战斗', 0, { agility: 1, perception: 1 }),
  'combat.pvp.draw': rule('玩家对战平局', '战斗', 0, { constitution: 1, spirit: 1 }),
  'pvp.warrant_reward_added': rule('追加通缉令赏金', '交易', 0, { spirit: 1, intelligence: 1 }),
  'npc.spar.victory': rule('域民切磋胜利', '交互', 10, { strength: 1, intelligence: 1, perception: 1 }, 30, 24),
  'npc.spar.defeat': rule('域民切磋落败', '交互', 0, { constitution: 1, spirit: 1 }),
  'npc.spar.escaped': rule('结束域民切磋', '交互', 0, { agility: 1, perception: 1 }),
  'npc.spar.timeout': rule('域民切磋超时', '交互', 0, { constitution: 1, spirit: 1 }),
  'npc.affinity_chat': rule('与域民有效交谈', '交互', 1, { spirit: 2, perception: 1 }, 10, 24),
  'npc.affinity_gained': rule('与域民互动并提升好感', '交互', 0, { spirit: 1, perception: 1 }),
  'npc.affinity_reward_granted': rule('获得域民任务好感奖励', '交互', 0, { spirit: 1, perception: 1 }),
  'party.created': rule('创建冒险队伍', '交互', 0, { spirit: 1, intelligence: 1 }),
  'party.joined': rule('加入冒险队伍', '交互', 0, { spirit: 1, perception: 1 }),
  'party.left': rule('离开冒险队伍', '交互', 0, { spirit: 1, intelligence: 1 }),
  'party.renamed': rule('变更队伍名称', '交互', 0, { spirit: 1, intelligence: 1 }),
  'party.leadership_transferred': rule('移交队伍队长', '交互', 0, { spirit: 1, intelligence: 1 }),
  'negotiation.talked': rule('与魔物交涉', '交互', 1, { spirit: 1, intelligence: 1, perception: 1 }, 10, 1),
  'negotiation.gifted': rule('向魔物交付交涉礼物', '交互', 0, { spirit: 1, perception: 1 }),
  'negotiation.succeeded': rule('和平结束魔物遭遇', '交互', 10, { spirit: 2, intelligence: 1, perception: 1 }, 30, 1),
  'negotiation.failed': rule('交涉破裂进入战斗', '交互', 0, { spirit: 1, constitution: 1 }),
  'negotiation.fought': rule('主动结束交涉开战', '交互', 0, { strength: 1, spirit: 1 }),
  'negotiation.left': rule('暂时结束交涉', '交互', 0, { spirit: 1, perception: 1 }),
  'social.friend_request.created': rule('送出好友申请', '交互', 0, { spirit: 1, perception: 1 }),
  'social.friend.accepted': rule('接受好友申请', '交互', 0, { spirit: 1 }),
  'social.friend.rejected': rule('拒绝好友申请', '交互', 0, { spirit: 1, perception: 1 }),
  'social.friend_interaction': rule('与好友互动', '交互', 1, { spirit: 2, perception: 1 }, 10, 24),
  'social.affinity_gift': rule('赠送亲密礼物', '交互', 0, { spirit: 2, perception: 1 }),
  'social.oath.ceremony_pending': rule('约定星誓仪式', '交互', 0, { spirit: 1 }),
  'social.oath.rejected': rule('拒绝星誓申请', '交互', 0, { spirit: 1, perception: 1 }),
  'social.oath.started': rule('缔结星誓', '交互', 10, { spirit: 2, perception: 1 }, 10),
  'social.oath.memory': rule('留下星誓纪念', '交互', 1, { spirit: 1, perception: 1 }, 10, 24),
  'social.oath.release_requested': rule('请求解除星誓', '交互', 0, { spirit: 1, intelligence: 1 }),
  'social.oath.released': rule('解除星誓', '交互', 0, { spirit: 1, intelligence: 1 }),
  'social.oath.release_rejected': rule('拒绝解除星誓', '交互', 0, { spirit: 1, constitution: 1 }),
  'home.purchased': rule('购得家园', '生活', 0, { intelligence: 1, perception: 1 }),
  'home.entered': rule('进入家园', '生活', 0, { agility: 1, perception: 1 }),
  'home.left': rule('离开家园', '生活', 0, { agility: 1 }),
  'home.renamed': rule('家园改名', '生活', 0, { spirit: 1, intelligence: 1 }),
  'home.upgraded': rule('升级家园', '生活', 10, { intelligence: 1, strength: 1 }, 30),
  'home.expanded': rule('扩建家园', '生活', 10, { intelligence: 1, strength: 1 }, 20),
  'home.furniture_crafted': rule('制作并摆放家具', '生活', 2, { intelligence: 1, strength: 1, perception: 1 }, 20),
  'home.furniture_removed': rule('拆除家具', '生活', 0, { strength: 1, perception: 1 }),
  'home.offer_traded': rule('在家园兑换物品', '交易', 0, { intelligence: 1, perception: 1 }),
  'home.storage_deposited': rule('存入家园仓储', '生活', 0, { intelligence: 1, perception: 1 }),
  'equipment.equipped': rule('穿戴装备', '生活', 0, { strength: 1, intelligence: 1 }),
  'equipment.unequipped': rule('卸下装备', '生活', 0, { intelligence: 1, perception: 1 }),
  'character.rest_started': rule('开始休息', '生活', 0, { constitution: 1, spirit: 1 }),
  'character.rest_ended': rule('结束休息', '生活', 0, { constitution: 1, agility: 1 }),
  'item.used.recovery': rule('使用恢复道具', '生活', 0, { constitution: 1, spirit: 1 }),
  'item.used.food': rule('食用增益食物', '生活', 0, { constitution: 1, perception: 1 }),
  'item.used.battle_elixir': rule('使用战斗药剂', '战斗', 0, { spirit: 1, intelligence: 1 }),
  'item.used.blueprint_box': rule('开启图纸盲盒', '生活', 0, { intelligence: 1, perception: 1 }),
  'item.used.other': rule('使用道具', '生活', 0, { perception: 1 }),
  'npc_shop.bought': rule('在店铺购买物品', '交易', 0, { intelligence: 1, perception: 1 }),
  'npc_shop.sold_equipment': rule('向店铺出售装备', '交易', 0, { intelligence: 1, perception: 1 }),
  'npc_shop.sold_material': rule('向店铺出售材料', '交易', 0, { intelligence: 1, perception: 1 }),
  'item.codex_discovered': rule('发现店铺成品图鉴', '探索', 0, { intelligence: 1, perception: 1 }),
  'guild_shop.bought': rule('在公会商店兑换物品', '交易', 0, { intelligence: 1, perception: 1 }),
  'guild_shop.sold': rule('向公会商店交付物品', '交易', 0, { intelligence: 1, perception: 1 }),
  'bookshop.bought': rule('在书店购买书籍', '交易', 0, { intelligence: 1, perception: 1 }),
  'bookshop.sold': rule('向书店出售书籍', '交易', 0, { intelligence: 1, perception: 1 }),
  'bookshop.skill_book_read': rule('研读技能书', '成长', 2, { intelligence: 2, perception: 1 }, 20),
  'skill.passive_link_changed': rule('调整被动技能协同链接', '成长', 0, { intelligence: 1, perception: 1 }),
  'mail.attachments_claimed': rule('领取邮件附件', '生活', 0, { perception: 1 }),
  'mail.deleted': rule('删除邮件', '生活', 0, { intelligence: 1 }),
  'inventory.material_discarded': rule('丢弃材料', '生活', 0, { intelligence: 1, perception: 1 }),
  'inventory.chest_opened': rule('开启宝箱', '探索', 0, { perception: 1, agility: 1 }),
  'craft.equipment_repaired': rule('修复装备耐久', '生活', 0, { strength: 1, intelligence: 1 }),
  'craft.repair_kit_made': rule('制作锻造维修包', '生活', 2, { strength: 1, intelligence: 1 }, 20, 1),
  'craft.refined': rule('精炼装备成功', '生活', 2, { strength: 1, intelligence: 1, perception: 1 }, 30, 1),
  'craft.refinement_failed': rule('精炼失败但消耗材料', '生活', 0, { strength: 1, perception: 1 }),
  'craft.fused': rule('熔铸装备成功', '生活', 2, { strength: 1, intelligence: 1, perception: 1 }, 30, 1),
  'craft.fusion_failed': rule('熔铸失败但消耗材料', '生活', 0, { strength: 1, perception: 1 }),
  'craft.reforged': rule('重铸装备', '生活', 5, { strength: 1, intelligence: 1, perception: 1 }, 30, 1),
  'craft.purified': rule('提纯材料', '生活', 2, { intelligence: 2, perception: 1 }, 40, 1),
  'craft.purification_failed': rule('提纯无产物', '生活', 0, { intelligence: 1, perception: 1 }),
  'alchemy.formula_saved': rule('保存炼金快捷配方', '生活', 0, { intelligence: 1, perception: 1 }),
  'alchemy.formula_renamed': rule('修改炼金配方名称', '生活', 0, { intelligence: 1 }),
  'alchemy.formula_deleted': rule('删除炼金快捷配方', '生活', 0, { intelligence: 1 }),
  'hunter_shop.bought': rule('在猎人小屋购买物品', '交易', 0, { intelligence: 1, perception: 1 }),
  'hunter_shop.sold': rule('向猎人小屋出售物品', '交易', 0, { intelligence: 1, perception: 1 }),
  'restaurant.meal_enjoyed': rule('在公会餐厅用餐', '生活', 0, { constitution: 1, perception: 1 }),
  'reward.new_world_claimed': rule('领取新世界成长奖励', '成长', 0, { spirit: 1, perception: 1 }),
  'quest.alchemy_creation_learned': rule('完成点灵教学', '委托', 10, { intelligence: 2, spirit: 1 }, 10),
  'world_site.commission_accepted': rule('接取站点委托', '委托', 0, { spirit: 1, perception: 1 }),
  'world_site.commission_notice': rule('留下站点委托交接通知', '委托', 0, { spirit: 1, perception: 1 }),
  'world_site.commission_completed': rule('完成站点委托交接', '委托', 10, { spirit: 1, agility: 1, perception: 1 }, 60, 1),
  'world_site.commission_claimed': rule('领取站点委托报酬', '委托', 0, { intelligence: 1, spirit: 1 }),
  'world_site.forecast': rule('查阅站点天气预报', '探索', 0, { intelligence: 1, perception: 1 }),
  'world_site.exchange': rule('在站点交换区域材料', '交易', 0, { intelligence: 1, perception: 1 }),
  'world_site.clues': rule('在站点调阅线索', '探索', 0, { intelligence: 1, perception: 1 }),
  'world_site.shelter': rule('在站点领取天气庇护', '探索', 0, { constitution: 1, perception: 1 }),
  'encounter.patrol_accepted': rule('接手域民巡查', '交互', 0, { spirit: 1, perception: 1 }),
  'encounter.discovered': rule('发现动态奇遇', '探索', 0, { perception: 1 }),
  'encounter.scene_joined': rule('加入公共奇遇', '交互', 0, { spirit: 1, perception: 1 }),
  'encounter.scene_contributed': rule('参与公共奇遇协作', '交互', 2, { spirit: 1, intelligence: 1, perception: 1 }, 20, 1),
  'encounter.scene_rewarded': rule('公共奇遇协作报酬结算', '交互', 0, { spirit: 1 }),
  'encounter.decision': rule('在奇遇中作出选择', '探索', 0, { spirit: 1, intelligence: 1 }),
  'encounter.resolved': rule('结算动态奇遇', '探索', 10, { spirit: 1, intelligence: 1, perception: 1 }, 50, 1),
  'quest.dungeon_secret_started': rule('开启地下迷宫支线', '委托', 0, { perception: 1 }),
  'quest.dungeon_secret_stage': rule('推进地下迷宫支线', '委托', 0, { spirit: 1, perception: 1 }),
  'quest.dungeon_secret_completed': rule('完成地下迷宫支线', '委托', 30, { strength: 1, spirit: 1, perception: 1 }, 30),
  'exploration.dungeon_entrance_marked': rule('标记地下迷宫入口', '探索', 2, { intelligence: 1, perception: 2 }, 20),
  'profession.advanced_quest_accepted': rule('接取二转试炼', '委托', 0, { spirit: 1, perception: 1 }),
  'profession.advanced_quest_abandoned': rule('中断二转试炼', '委托', 0, { spirit: 1, intelligence: 1 }),
  'profession.advanced_quest_stage': rule('推进二转试炼', '委托', 0, { strength: 1, spirit: 1, perception: 1 }),
  'profession.advanced_trial_started': rule('开始导师试炼', '战斗', 0, { strength: 1, spirit: 1 }),
  'profession.advanced_completed': rule('完成二转试炼', '成长', 30, { spirit: 1, strength: 1, intelligence: 1 }, 30, 24),
  'profession.hidden_completed': rule('完成隐藏二转', '成长', 30, { spirit: 2, intelligence: 1, perception: 1 }, 30, 24),
  'quest.hidden_stage_accepted': rule('接取隐藏职业委托', '委托', 0, { spirit: 1, perception: 1 }),
  'quest.hidden_materials_prepared': rule('备齐隐藏职业委托材料', '委托', 0, { intelligence: 1, perception: 1 }),
  'quest.hidden_lesson_advanced': rule('推进隐藏职业教学', '委托', 0, { intelligence: 1, spirit: 1 }),
  'quest.hidden_stage_completed': rule('完成隐藏职业委托一环', '委托', 2, { spirit: 1, intelligence: 1, perception: 1 }, 20),
  'quest.hidden_observation': rule('记录隐藏职业试炼观察', '委托', 0, { intelligence: 1, perception: 1 }),
  'instance_market.listed': rule('发布实例寄售', '交易', 0, { intelligence: 1, perception: 1 }),
  'instance_market.cancelled': rule('撤回实例寄售', '交易', 0, { intelligence: 1, perception: 1 }),
  'instance_market.expired': rule('实例寄售到期', '交易', 0, { intelligence: 1, perception: 1 }),
  'instance_market.bought': rule('实例寄售买入成交', '交易', 0, { intelligence: 1, perception: 1 }),
  'instance_market.sold': rule('实例寄售卖出成交', '交易', 0, { intelligence: 1, perception: 1 }),
  'talent.configuration': rule('调整天赋配置', '成长', 0, { intelligence: 1, perception: 1 }),
  'talent.social': rule('以天赋完成交互', '交互', 1, { spirit: 2, perception: 1 }, 10, 24),
  'talent.reward_settled': rule('领取天赋活动成果', '生活', 0, { spirit: 1, intelligence: 1 }),
  'talent.activity_settled': rule('完成天赋活动阶段', '生活', 1, { intelligence: 1, spirit: 1, perception: 1 }, 10, 1),
  'social.blessing.claimed': rule('完成教堂祈福', '交互', 1, { spirit: 2, perception: 1 }, 10, 24),
  'item.quick_slot_changed': rule('调整道具快捷栏', '成长', 0, { agility: 1, intelligence: 1 }),
  'opening.route_chosen': rule('选择初行道路', '成长', 0, { spirit: 1, perception: 1 }),
  'device.activated': rule('启用异械', '成长', 0, { intelligence: 1, agility: 1 }),
  'device.deactivated': rule('停用异械', '成长', 0, { intelligence: 1, agility: 1 }),
  'device.quick_slot_changed': rule('调整异械快捷栏', '成长', 0, { intelligence: 1, agility: 1 }),
  'companion.accepted': rule('接纳随从', '交互', 2, { spirit: 2, perception: 1 }, 20),
  'companion.declined': rule('婉拒随从邀请', '交互', 0, { spirit: 1, perception: 1 }),
  'companion.deployed': rule('安排随从出行', '交互', 0, { spirit: 1, perception: 1 }),
  'companion.recalled': rule('召回随从休整', '交互', 0, { spirit: 1, intelligence: 1 }),
  'companion.released': rule('放归随从', '交互', 0, { spirit: 1 }),
  'companion.renamed': rule('为随从改名', '交互', 0, { spirit: 1 }),
  'companion.fed': rule('喂养随从', '交互', 1, { spirit: 2, constitution: 1 }, 10, 24),
  'companion.specialty_changed': rule('调整随从专长', '交互', 0, { intelligence: 1, perception: 1 }),
  'companion.bread_shared': rule('与黄金兔分享面包', '交互', 0, { spirit: 1, constitution: 1 }),
  'opening.aqua_story_advanced': rule('推进阿库娅同行剧情', '交互', 0, { spirit: 1, perception: 1 }),
  'opening.aqua_commission_completed': rule('完成阿库娅调查委托', '委托', 10, { spirit: 2, intelligence: 1 }, 10),
  'opening.aqua_follow_changed': rule('调整阿库娅同行安排', '交互', 0, { spirit: 1, intelligence: 1 }),
  'quest.girl_gratitude_stage': rule('推进梨子喵的谢意', '委托', 0, { spirit: 1, perception: 1 }),
  'travel.world_gate_used': rule('通过界门旅行', '探索', 0, { agility: 1, perception: 1 }),
  'craft.automaton_batch_succeeded': rule('机巧制作批次成功', '生活', 5, { intelligence: 2, spirit: 1, perception: 1 }, 40, 1),
  'craft.automaton_batch_failed': rule('机巧制作批次失败但耗材', '生活', 0, { intelligence: 1, perception: 1 }),
  'automaton.cultivated': rule('培养机巧', '生活', 2, { spirit: 1, intelligence: 1, perception: 1 }, 20, 1),
  'automaton.respecced': rule('重调机巧育成', '生活', 0, { intelligence: 1, perception: 1 }),
  'automaton.repaired': rule('维修机巧', '生活', 0, { intelligence: 1, strength: 1 }),
  'automaton.state_changed': rule('调整机巧状态', '交互', 0, { spirit: 1, intelligence: 1 }),
  'automaton.greeted': rule('与机巧交谈', '交互', 1, { spirit: 2, perception: 1 }, 10, 24),
  'automaton.quote_rated': rule('评价机巧语录', '交互', 0, { spirit: 1, perception: 1 }),
  'automaton.memory_saved': rule('收藏机巧语录', '交互', 0, { spirit: 1 }),
  'automaton.memory_forgotten': rule('取消收藏机巧语录', '交互', 0, { spirit: 1 }),
  'automaton.portrait_submitted': rule('提交机巧形象审核', '交互', 0, { spirit: 1, intelligence: 1 }),
  'automaton.portrait_reset': rule('恢复机巧默认形象', '交互', 0, { spirit: 1 }),
  'automaton.portrait_approved': rule('机巧形象审核通过', '交互', 0, { spirit: 1 }),
  'automaton.portrait_rejected': rule('机巧形象审核未通过', '交互', 0, { spirit: 1 }),
  'profession.inheritance_study_started': rule('开始传承旁修', '成长', 0, { intelligence: 1, spirit: 1 }),
  'profession.inheritance_study_completed': rule('完成传承旁修', '成长', 10, { intelligence: 2, spirit: 1 }, 20, 24),
  'profession.inheritance_study_equipped': rule('调整旁修传承', '成长', 0, { intelligence: 1, spirit: 1 }),
  'quest.story_stage': rule('推进角色剧情', '委托', 0, { spirit: 1, perception: 1 }),
  'quest.forest_guide_choice': rule('决定是否同行迎战森林史莱姆', '委托', 0, { spirit: 1, perception: 1 }),
  'quest.lamplight_action': rule('推进灯火旅途', '委托', 0, { spirit: 1, intelligence: 1, perception: 1 }),
  'combat.story_duel_started': rule('开始艾森约战', '战斗', 0, { strength: 1, spirit: 1 }),
  'combat.story_duel.victory': rule('艾森约战胜利', '战斗', 10, { strength: 1, spirit: 1, perception: 1 }, 10),
  'combat.story_duel.defeat': rule('艾森约战落败', '战斗', 0, { constitution: 1, spirit: 1 }),
  'combat.story_duel.escaped': rule('离开艾森约战', '战斗', 0, { agility: 1, perception: 1 }),
  'combat.story_duel.timeout': rule('艾森约战超时', '战斗', 0, { constitution: 1, spirit: 1 }),
  'quest.floating_rescue_accepted': rule('接取浮叶镇救援', '委托', 0, { spirit: 1, perception: 1 }),
  'quest.floating_rescue_reported': rule('完成浮叶镇救援复命', '委托', 0, { spirit: 1, intelligence: 1 }),
  'travel.rescue_returned': rule('带获救者返程', '探索', 0, { agility: 1, spirit: 1 }),
  'opening.started': rule('开始异世界初行', '成长', 0, { spirit: 1, perception: 1 }),
  'opening.branch_chosen': rule('作出初行选择', '成长', 0, { spirit: 1, intelligence: 1 }),
  'opening.treated': rule('在初行中使用草药', '生活', 0, { constitution: 1, perception: 1 }),
  'opening.arrived': rule('完成初行抵达', '探索', 0, { agility: 1, perception: 1 }),
  'opening.completed': rule('完成异世界初行', '成长', 0, { spirit: 1, perception: 1 }),
  'opening.keepsake_settled': rule('办理初行凭物', '交互', 0, { spirit: 1, intelligence: 1 }),
  'opening.job_accepted': rule('推进初行委托', '委托', 0, { spirit: 1, perception: 1 }),
  'opening.job_settled': rule('结算初行委托', '委托', 2, { spirit: 1, intelligence: 1 }, 20),
  'opening.guild_service_used': rule('核销初行公会服务', '生活', 0, { intelligence: 1, perception: 1 }),
  'opening.guild_entered': rule('进入初行公会', '探索', 0, { agility: 1, perception: 1 }),
  'opening.guild_left': rule('离开初行公会', '探索', 0, { agility: 1 }),
  'opening.weapon_claimed': rule('领取初行职业武器', '成长', 0, { strength: 1, perception: 1 }),
  'opening.lesson_completed': rule('完成公会入门练习', '成长', 1, { intelligence: 1, perception: 1 }, 10),
  'npc.first_met': rule('与域民初次相识', '交互', 0, { spirit: 1, perception: 1 }),
  'opening.coupon_redeemed': rule('兑换初行凭单', '交易', 0, { intelligence: 1, perception: 1 }),
  'travel.guild_transport': rule('乘坐公会接驳舱', '探索', 0, { agility: 1, perception: 1 }),
  'quest.omniscient_accepted': rule('接取全知者观察委托', '委托', 0, { intelligence: 1, perception: 1 }),
  'quest.omniscient_completed': rule('完成全知者观察委托', '委托', 10, { intelligence: 2, perception: 1 }, 10),
  'quest.omniscient_claimed': rule('领取全知者资格', '成长', 0, { intelligence: 1, perception: 1 }),
  'achievement.unlocked': rule('达成成就', '成长', 0, { spirit: 1, perception: 1 }),
  'achievement.box_opened': rule('开启成就道具匣', '生活', 0, { perception: 1 }),
  'profession.hidden_loadout_changed': rule('调整隐藏职业阵列', '战斗', 0, { intelligence: 1, perception: 1 }),
  'profession.hidden_auto_saved': rule('保存隐藏技能自动配置', '战斗', 0, { intelligence: 1, perception: 1 }),
  'combat.auto_config_changed': rule('调整自动战斗配置', '战斗', 0, { intelligence: 1, perception: 1 }),
  'quest.goblin_king.accepted': rule('接取失踪少女主线', '委托', 0, { spirit: 1, perception: 1 }),
  'quest.goblin_king.stage': rule('推进失踪少女主线', '委托', 0, { spirit: 1, perception: 1 }),
  'quest.goblin_king.completed': rule('完成失踪少女主线', '委托', 30, { strength: 1, spirit: 1, perception: 1 }, 30),
  'quest.evolution.stage': rule('推进进化主线', '委托', 0, { intelligence: 1, perception: 1 }),
  'quest.evolution.completed': rule('完成进化主线试炼', '委托', 30, { constitution: 1, spirit: 1, intelligence: 1 }, 30),
  'quest.realm_barrier.stage': rule('推进境界瓶颈线索', '委托', 0, { spirit: 1, perception: 1 }),
  'evolution.seed_awakened': rule('进化之种觉醒', '成长', 0, { constitution: 1, spirit: 1 }),
  'evolution.injected': rule('注射进化剂并突破生长结', '成长', 10, { constitution: 2, spirit: 1, perception: 1 }, 10),
  'evolution.observation_accepted': rule('接取进化观察', '委托', 0, { intelligence: 1, perception: 1 }),
  'evolution.observation_completed': rule('完成进化观察目标', '委托', 0, { intelligence: 1, perception: 1 }),
  'evolution.observation_claimed': rule('交付进化观察报告', '委托', 2, { intelligence: 1, perception: 2 }, 10),
  'evolution.mutation_paused': rule('暂停变异影响', '成长', 0, { constitution: 1, intelligence: 1 }),
  'evolution.mutation_resumed': rule('恢复变异影响', '成长', 0, { constitution: 1, intelligence: 1 }),
  'evolution.mutation_stabilized': rule('稳定变异', '成长', 5, { constitution: 1, intelligence: 1, perception: 1 }, 20),
  'evolution.mutation_archived': rule('封存变异', '成长', 0, { intelligence: 1, spirit: 1 }),
  'realm.barrier_broken': rule('突破初心境界', '成长', 0, { spirit: 1, perception: 1 }),
  'bank.deposited': rule('存入钱庄活期', '交易', 0, { intelligence: 1 }),
  'bank.withdrawn': rule('从钱庄取款', '交易', 0, { intelligence: 1 }),
  'bank.term_opened': rule('开立定期存单', '交易', 0, { intelligence: 1, perception: 1 }),
  'bank.term_matured': rule('定期存单到期结算', '交易', 1, { intelligence: 1, perception: 1 }, 10),
  'bank.term_early': rule('提前支取定期存单', '交易', 0, { intelligence: 1 }),
  'finance.share_bought': rule('买入势力份额', '交易', 0, { intelligence: 1, perception: 1 }),
  'finance.share_sold': rule('卖出势力份额', '交易', 0, { intelligence: 1, perception: 1 }),
  'finance.mission_accepted': rule('接取势力委托', '委托', 0, { spirit: 1, intelligence: 1 }),
  'finance.mission_completed': rule('完成势力委托', '委托', 30, { spirit: 1, intelligence: 1, perception: 1 }, 30),
  'dungeon.entered': rule('进入地下迷宫', '探索', 0, { constitution: 1, perception: 1 }),
  'dungeon.left': rule('离开地下迷宫', '探索', 0, { agility: 1, perception: 1 }),
  'dungeon.floor_changed': rule('抵达迷宫楼层', '探索', 0, { constitution: 1, agility: 1, perception: 1 }),
  'dungeon.trap_triggered': rule('触发迷宫陷阱', '探索', 0, { constitution: 1, perception: 1 }),
  'dungeon.chest_opened': rule('开启迷宫宝箱', '探索', 2, { perception: 2, agility: 1 }, 20),
  'travel.arrived': rule('抵达移动目的地', '探索', 0, { agility: 1, constitution: 1 }),
  'travel.cancelled': rule('取消移动或寻怪', '探索', 0, { perception: 1 }),
  'travel.target_lost': rule('寻怪目标已消失', '探索', 0, { perception: 1 }),
  'resource.mining_started': rule('开始采集资源', '探索', 0, { constitution: 1, perception: 1 }),
  'resource.mining_cancelled': rule('取消资源采集', '探索', 0, { perception: 1 }),
  'resource.mined': rule('完成资源采集', '探索', 2, { constitution: 1, strength: 1, perception: 1 }, 50, 1),
  'resource.mined_empty': rule('采集完成但无所得', '探索', 0, { constitution: 1, perception: 1 }),
  'craft.forged': rule('打造装备', '生活', 10, { strength: 2, intelligence: 1, perception: 1 }, 60, 1),
  'craft.forge_failed': rule('打造失败但消耗材料', '生活', 0, { strength: 1, perception: 1 }),
  'craft.epic_forged': rule('打造史诗装备', '生活', 30, { strength: 2, intelligence: 1, perception: 1 }, 60),
  'craft.alchemy_succeeded': rule('炼金批次炼成', '生活', 5, { intelligence: 2, spirit: 1, perception: 1 }, 50, 1),
  'craft.alchemy_failed': rule('炼金批次失败但消耗材料', '生活', 0, { intelligence: 1, perception: 1 }),
  'craft.constructed_device': rule('构造异械', '生活', 5, { intelligence: 2, perception: 1, agility: 1 }, 50, 1),
  'craft.constructed_material': rule('构造材料', '生活', 2, { intelligence: 1, perception: 1 }, 30, 1),
  'craft.construction_failed': rule('构造失败但消耗材料', '生活', 0, { intelligence: 1, perception: 1 }),
  'craft.deconstructed': rule('完成分解', '生活', 2, { intelligence: 1, perception: 2 }, 50, 1),
  'craft.deconstruct_empty': rule('分解无可用产物', '生活', 0, { intelligence: 1, perception: 1 }),
  'skill.learned': rule('学习技能', '成长', 5, { intelligence: 1, spirit: 1, perception: 1 }, 30),
  'skill.upgraded': rule('升级技能', '成长', 2, { intelligence: 1, spirit: 1 }, 30),
  'skill.specialization_upgraded': rule('升级技能专精', '成长', 2, { intelligence: 1, perception: 1 }, 30),
  'skill.appraisal_upgraded': rule('升级鉴识', '成长', 2, { intelligence: 1, perception: 1 }, 30),
  'skill.shortcut_changed': rule('调整技能快捷栏', '成长', 0, { agility: 1, intelligence: 1 }),
  'skill.discovered': rule('领悟技能', '成长', 2, { intelligence: 1, perception: 1 }, 20),
  'skill.allocation_reset': rule('重置技能投入', '成长', 0, { intelligence: 1, spirit: 1 }),
};

/** 将整笔积分按六维权重分配，整数余数由固定六维顺序分派，确保守恒。 */
export const allocateOperationPoints = (totalUnits: number, weight: Allocation): Allocation => {
  const positive = attributes.map(key => Math.max(0, Math.floor(Number(weight[key]) || 0)));
  const sum = positive.reduce((a, b) => a + b, 0);
  const result = weights({});
  if (!sum || totalUnits <= 0) return result;
  for (let index = 0; index < attributes.length; index++) result[attributes[index]] = Math.floor(totalUnits * positive[index] / sum);
  const order = attributes.map((key, index) => ({ key, index, remainder: totalUnits * positive[index] % sum })).filter(entry => positive[entry.index] > 0)
    .sort((a, b) => b.remainder - a.remainder || a.index - b.index);
  for (let rest = totalUnits - attributes.reduce((count, key) => count + result[key], 0), index = 0; rest > 0; rest--, index++) result[order[index % order.length].key]++;
  return result;
};
