import { randomUUID } from 'node:crypto';
import type { Pool, PoolConnection, RowDataPacket, ResultSetHeader } from 'mysql2/promise';
import { getPool, withTransaction } from '../database/pool';
import { recordCharacterOperation } from './character-operation.service';
import { grantOpeningItem } from './opening.service';
import { buildNpcSparProfile, recalculateNpcSparProfileStats } from './npc-sparring.config';
import { recalculateCharacterStats } from './character.service';
import { advancedResourceForProfession } from './advanced-resource.config';
import { assertOpeningFree } from './opening-state';
import { snapshotCombatEnvironment } from './world-dynamics.service';
import { aevierTour, aevierChallenge, aesonVictory } from './worldtree-witness-content';
import { recordCardMovement, resetCardMovementCharge } from './monster-card-exploration.service';

type Db = Pool | PoolConnection;
type Witness = RowDataPacket & {id:number;name:string;level:number;realm_stage:number;region_code:string;current_region_id:number;pos_x:number;pos_y:number;pos_z:number;adventurer_registered:number;profession_code:string|null;destination_code:string|null;opening_state:string|null;tour_stage:number;challenge_stage:number;current_hp:number;current_mp:number;activity_status:string};
const tourCode='worldtree_witness_tour',challengeCode='worldtree_aeson';
const characterFor=async(c:Db,user:string,lock=false)=>{const[rows]=await c.execute<Witness[]>(`SELECT ch.*,r.code AS region_code,o.destination_code,o.state AS opening_state,
  COALESCE((SELECT stage FROM player_main_quest_progress WHERE character_id=ch.id AND quest_code=?),0) AS tour_stage,
  COALESCE((SELECT stage FROM player_main_quest_progress WHERE character_id=ch.id AND quest_code=?),0) AS challenge_stage
  FROM characters ch JOIN players p ON p.id=ch.player_id JOIN map_regions r ON r.id=ch.current_region_id
  LEFT JOIN player_opening_stories o ON o.character_id=ch.id WHERE p.qq_user_id=? LIMIT 1${lock?' FOR UPDATE':''}`,[tourCode,challengeCode,user]);return rows[0]??null;};
const isWitness=(ch:Witness|null)=>Boolean(ch?.destination_code==='world_tree'&&ch.opening_state==='completed');
const writeStage=async(c:PoolConnection,id:number,code:string,stage:number)=>{await c.execute('INSERT INTO player_main_quest_progress (character_id,quest_code,stage) VALUES (?,?,?) ON DUPLICATE KEY UPDATE stage=VALUES(stage),updated_at=NOW()',[id,code,stage]);await recordCharacterOperation(c,{characterId:id,kind:'quest.story_stage',source:{system:'worldtree_witness_quest',id:`${id}:${code}`,step:`stage_${stage}`},outcome:'推进',summary:`推进${code}剧情至第 ${stage} 幕`,detail:{questCode:code,stage}});};
const tourScene=(stage:number)=>({kind:'tour' as const,stage,total:aevierTour.length,...aevierTour[stage-1]!});
const challengeScene=(stage:number)=>({kind:'challenge' as const,stage,total:aevierChallenge.length,...aevierChallenge[stage-1]!});

export const worldtreeWitnessState=async(user:string)=>{const c=await characterFor(await getPool(),user);if(!isWitness(c)||!c)return null;return{tour:Number(c.tour_stage),challenge:Number(c.challenge_stage),ready:Boolean(c.adventurer_registered&&c.profession_code),atGuild:c.region_code==='world_tree'&&Number(c.pos_x)===-5&&Number(c.pos_y)===-3&&Number(c.pos_z)===0};};
export const currentWorldtreeTour=async(user:string)=>{const s=await worldtreeWitnessState(user);return s&&s.tour>0&&s.tour<aevierTour.length?tourScene(s.tour):null;};
export const startWorldtreeTour=async(user:string)=>withTransaction(async c=>{const ch=await characterFor(c,user,true);if(!isWitness(ch)||!ch||!ch.adventurer_registered||!ch.profession_code||Number(ch.tour_stage)!==0||ch.region_code!=='world_tree'||Number(ch.pos_x)!==-5||Number(ch.pos_y)!==-3)return null;
  await writeStage(c,ch.id,tourCode,1);await c.execute('DELETE FROM player_opening_visits WHERE character_id=?',[ch.id]);const[owned]=await c.execute<RowDataPacket[]>("SELECT 1 FROM player_inventory p JOIN item_definitions i ON i.id=p.item_id WHERE p.character_id=? AND i.code='map_world_tree' AND p.quantity>0",[ch.id]);if(!owned.length)await grantOpeningItem(c,ch.id,'map_world_tree');return tourScene(1);});
export const continueWorldtreeTour=async(user:string,expectedStage?:number)=>withTransaction(async c=>{const ch=await characterFor(c,user,true);if(!isWitness(ch)||!ch||Number(ch.tour_stage)<1)throw new Error('艾薇儿还没有邀请你同行。');if(expectedStage!==undefined&&expectedStage!==Number(ch.tour_stage)||Number(ch.tour_stage)>=aevierTour.length)return tourScene(Math.min(Number(ch.tour_stage),aevierTour.length));const next=Number(ch.tour_stage)+1;const page=aevierTour[next-1]!;
  await c.execute('UPDATE characters SET pos_x=?,pos_y=? WHERE id=? AND current_region_id=?',[page.x,page.y,ch.id,ch.current_region_id]);
  if(next===2){const[owned]=await c.execute<RowDataPacket[]>("SELECT 1 FROM player_inventory p JOIN item_definitions i ON i.id=p.item_id WHERE p.character_id=? AND i.code='map_worldtree_meadow' AND p.quantity>0",[ch.id]);if(!owned.length)await grantOpeningItem(c,ch.id,'map_worldtree_meadow');}
  await writeStage(c,ch.id,tourCode,next);return tourScene(next);});
export const assertWorldtreeTourFreeAction=async(c:Db,id:number)=>{const[rows]=await c.execute<(RowDataPacket&{stage:number})[]>(`SELECT q.stage FROM player_main_quest_progress q JOIN player_opening_stories o ON o.character_id=q.character_id WHERE q.character_id=? AND q.quest_code=? AND o.destination_code='world_tree' AND o.state='completed' LIMIT 1`,[id,tourCode]);if(rows[0]&&Number(rows[0].stage)<aevierTour.length)throw new Error('艾薇儿正在带你游览世界树，请先继续当前剧情。');};

export const startAevierChallenge=async(user:string)=>withTransaction(async c=>{const ch=await characterFor(c,user,true);if(!isWitness(ch)||!ch||Number(ch.tour_stage)<aevierTour.length||Number(ch.level)<11||Number(ch.realm_stage)<2)throw new Error('先完成世界树初游与十一级突破。');if(ch.region_code!=='world_tree'||Number(ch.pos_x)!==-5||Number(ch.pos_y)!==-3||Number(ch.pos_z)!==0)throw new Error('请先回到世界树冒险者公会门前（-5，-3），艾薇儿的纸条留在那里。');if(Number(ch.challenge_stage)>0)return challengeScene(Math.min(Number(ch.challenge_stage),aevierChallenge.length));
  await writeStage(c,ch.id,challengeCode,1);return challengeScene(1);});
export const continueAevierChallenge=async(user:string,expectedStage?:number)=>withTransaction(async c=>{const ch=await characterFor(c,user,true);if(!isWitness(ch)||!ch||Number(ch.challenge_stage)<1)throw new Error('现在没有待继续的艾薇儿剧情。');if(expectedStage!==undefined&&expectedStage!==Number(ch.challenge_stage)||Number(ch.challenge_stage)>=aevierChallenge.length)return challengeScene(Math.min(Number(ch.challenge_stage),aevierChallenge.length));const next=Number(ch.challenge_stage)+1;await writeStage(c,ch.id,challengeCode,next);return challengeScene(next);});

export const worldtreeWitnessMainQuest=async(user:string)=>{const ch=await characterFor(await getPool(),user);if(!isWitness(ch)||!ch||!ch.adventurer_registered||!ch.profession_code)return null;
  if(Number(ch.tour_stage)<aevierTour.length)return Number(ch.tour_stage)>0?{title:'【主线·世界树初游】',description:'艾薇儿正在带我游览世界树。',action:{label:'[继续同行]',command:`/世界树见证 游览 ${ch.tour_stage}`}}:{title:'【主线·世界树初游】',description:'走出世界树公会时，根桥附近传来争执声。首次离会或移动会展开相遇。'};
  if(Number(ch.level)<11||Number(ch.realm_stage)<2)return null;
  if(!ch.challenge_stage)return{title:'【主线·艾薇儿的邀约】',description:'艾薇儿托公会留下纸条，约我再去看看世界树的新露台。先到公会门前赴约。',action:ch.region_code==='world_tree'&&Number(ch.pos_x)===-5&&Number(ch.pos_y)===-3?{label:'[赴约]',command:'/世界树见证 赴约'}:ch.region_code==='world_tree'?{label:'[前往公会]',command:'/前往 -5 -3 0'}:{label:'[前往世界树]',command:'/前往地图 map_world_tree'}};
  if(Number(ch.challenge_stage)<aevierChallenge.length)return{title:'【主线·艾薇儿的邀约】',description:'艾薇儿和艾森在根桥上发生争执。继续听他们说完。',action:{label:'[继续剧情]',command:`/世界树见证 邀约 ${ch.challenge_stage}`}};
  if(Number(ch.challenge_stage)===aevierChallenge.length)return{title:'【主线·狂拳的约战】',description:'艾森将力量压到 Lv.20，在永恒竞技场等我。可以与队友同行；只有我带领的队伍能发起这场任务战。战败后可再挑战。',action:ch.region_code==='eternal_arena'?{label:'[查看竞技场]',command:'/永恒竞技场'}:ch.region_code==='world_tree'&&Number(ch.pos_x)===6&&Number(ch.pos_y)===-4?{label:'[进入竞技场]',command:'/建筑进入 eternal_arena_gate'}:ch.region_code==='world_tree'?{label:'[前往竞技场]',command:'/前往 6 -4 0'}:{label:'[前往世界树]',command:'/前往地图 map_world_tree'}};
  return null;};

export const enterEternalArena=async(user:string)=>withTransaction(async c=>{const ch=await characterFor(c,user,true);if(!isWitness(ch)||!ch||Number(ch.challenge_stage)!==aevierChallenge.length)throw new Error('艾森尚未向你发出约战，或这场约战已经结束。');if(ch.region_code!=='world_tree'||Number(ch.pos_x)!==6||Number(ch.pos_y)!==-4||Number(ch.pos_z)!==0)throw new Error('请先前往世界树的永恒竞技场入口（6，-4）。');const[arena]=await c.execute<RowDataPacket[]>("SELECT id FROM map_regions WHERE code='eternal_arena' AND is_enabled=1 LIMIT 1",[]);if(!arena[0])throw new Error('永恒竞技场暂未开放。');
  const[party]=await c.execute<RowDataPacket[]>('SELECT pm.party_id,p.leader_character_id FROM party_members pm JOIN parties p ON p.id=pm.party_id WHERE pm.character_id=? FOR UPDATE',[ch.id]);if(party[0]&&Number(party[0].leader_character_id)!==ch.id)throw new Error('这场约战只能由剧情主角担任队长。');
  const[members]=party[0]?await c.execute<RowDataPacket[]>('SELECT ch.id,ch.name,ch.current_region_id,ch.pos_x,ch.pos_y,ch.pos_z,ch.activity_status FROM party_members pm JOIN characters ch ON ch.id=pm.character_id WHERE pm.party_id=? FOR UPDATE',[party[0].party_id]):[[ch]] as any;
  for(const member of members){if(Number(member.current_region_id)!==Number(ch.current_region_id)||Number(member.pos_x)!==6||Number(member.pos_y)!==-4||Number(member.pos_z)!==0)throw new Error('同行队友需全部抵达竞技场入口。');await assertOpeningFree(c,Number(member.id));await assertWorldtreeTourFreeAction(c,Number(member.id));const[busy]=await c.execute<RowDataPacket[]>(`SELECT EXISTS(SELECT 1 FROM player_travels WHERE character_id=?) OR EXISTS(SELECT 1 FROM combat_members cm JOIN combat_sessions cs ON cs.id=cm.session_id WHERE cm.character_id=? AND cs.state='active') AS busy`,[member.id,member.id]);if(busy[0]?.busy||member.activity_status!=='active')throw new Error(`队员「${member.name}」现在无法进入竞技场。`);}
  await c.execute(`UPDATE characters SET current_region_id=?,pos_x=420,pos_y=0,pos_z=0 WHERE id IN (${members.map(()=>'?').join(',')})`,[arena[0].id,...members.map(m=>m.id)]);
  for(const member of members)await recordCardMovement(c,Number(member.id),{regionId:Number(arena[0].id),z:0},{teleport:true});
  return '竞技场的拱门从世界树根旁展开。我和队友踏上铺着白砂的场地，四周看台有人认出狂狮团的副会长，议论声渐渐聚拢。艾森站在中央，袖口挽到手肘，手腕上绑着压制力量的符带。艾薇儿坐在最前排，见我抬头，朝我用力挥手。\n\n“想清楚就上来。”艾森活动拳指，“我按二十级的力量打。带了朋友，就让他们一起上。”';});
export const eternalArenaView=async(user:string)=>{const ch=await characterFor(await getPool(),user);if(!ch||ch.region_code!=='eternal_arena')throw new Error('现在不在永恒竞技场。');return{title:'永恒竞技场',canStart:isWitness(ch)&&Number(ch.challenge_stage)===aevierChallenge.length,text:'白砂场中央，艾森正缠紧拳带。符带把他的力量压在 Lv.20。他抬眼望向我和队友：“准备好了就开始。打完这一场，咱们把话说透。”\n\n这是剧情主角的个人任务战，随行队友可以参战。战败后仍可从世界树入口重试。'};};
export const leaveEternalArena=async(user:string)=>withTransaction(async c=>{const ch=await characterFor(c,user,true);if(!ch||ch.region_code!=='eternal_arena')throw new Error('你当前不在永恒竞技场。');const[busy]=await c.execute<RowDataPacket[]>("SELECT 1 FROM combat_members cm JOIN combat_sessions cs ON cs.id=cm.session_id WHERE cm.character_id=? AND cs.state='active' LIMIT 1",[ch.id]);if(busy[0])throw new Error('战斗尚未结束，不能离开竞技场。');const[tree]=await c.execute<RowDataPacket[]>("SELECT id FROM map_regions WHERE code='world_tree' LIMIT 1",[]);if(!tree[0])throw new Error('世界树归途暂不可用。');await c.execute('UPDATE characters SET current_region_id=?,pos_x=6,pos_y=-4,pos_z=0 WHERE id=?',[tree[0].id,ch.id]);await recordCardMovement(c,Number(ch.id),{regionId:Number(tree[0].id),z:0},{teleport:true});return '我从侧门回到世界树的根桥。艾森的约战还在，准备好后可以再次进入竞技场。';});

export const startAesonDuel=async(user:string)=>withTransaction(async c=>{const ch=await characterFor(c,user,true);if(!isWitness(ch)||!ch||ch.region_code!=='eternal_arena'||Number(ch.challenge_stage)!==aevierChallenge.length)throw new Error('请先接受艾森的约战并进入永恒竞技场。');if(ch.activity_status!=='active')throw new Error('请先恢复行动状态。');
  const[party]=await c.execute<RowDataPacket[]>('SELECT pm.party_id,p.leader_character_id FROM party_members pm JOIN parties p ON p.id=pm.party_id WHERE pm.character_id=? FOR UPDATE',[ch.id]);if(party[0]&&Number(party[0].leader_character_id)!==ch.id)throw new Error('剧情主角必须担任队长。');const[members]=party[0]?await c.execute<RowDataPacket[]>('SELECT ch.* FROM party_members pm JOIN characters ch ON ch.id=pm.character_id WHERE pm.party_id=? FOR UPDATE',[party[0].party_id]):[[ch]] as any;
  for(const member of members){if(Number(member.current_region_id)!==Number(ch.current_region_id)||Number(member.pos_x)!==420||Number(member.pos_y)!==0||Number(member.pos_z)!==0)throw new Error('请让所有队友在竞技场内集合。');const[busy]=await c.execute<RowDataPacket[]>(`SELECT EXISTS(SELECT 1 FROM player_travels WHERE character_id=?) OR EXISTS(SELECT 1 FROM combat_members cm JOIN combat_sessions cs ON cs.id=cm.session_id WHERE cm.character_id=? AND cs.state='active') AS busy`,[member.id,member.id]);if(busy[0]?.busy||member.activity_status!=='active'||Number(member.current_hp)<=0)throw new Error(`队员「${member.name}」现在无法参战。`);await recalculateCharacterStats(c,Number(member.id));}
  const[refreshed]=await c.execute<RowDataPacket[]>(`SELECT * FROM characters WHERE id IN (${members.map(()=>'?').join(',')}) ORDER BY id FOR UPDATE`,members.map(m=>m.id));
  const base=buildNpcSparProfile({code:'aeson_eternal_arena',name:'狂拳·艾森',description:'狂狮团副会长，拳法大师',region_code:'world_tree'},20,0);
  const profile={...base,name:'狂拳·艾森',level:20,band:[20,20],profession:'warrior',advancedCode:undefined,advancedName:'',advancedEffect:{},equipment:{...base.equipment,level:20,quality:75},evolution:{},injections:0};const stats=recalculateNpcSparProfileStats(profile);const finalProfile={...profile,...stats};
  const[template]=await c.execute<RowDataPacket[]>("SELECT id FROM monster_templates WHERE code='npc_sparring_dummy' LIMIT 1",[]);if(!template[0])throw new Error('剧情战斗数据尚未初始化。');const session=randomUUID();const[spawn]=await c.execute<ResultSetHeader>('INSERT INTO monster_spawns (template_id,region_id,pos_x,pos_y,pos_z,level,current_hp,skill_sequence,traits_json,defeated_at) VALUES (?,?,?,?,?,?,?,?,?,NOW())',[template[0].id,ch.current_region_id,420,0,0,20,finalProfile.stats.hpMax,JSON.stringify(['aeson_inspire','aeson_earthbreak','aeson_softbreak','aeson_shortfist','aeson_ironwill','aeson_snakebind','aeson_ultimate','aeson_berserk','aeson_destruction']),JSON.stringify([{code:'npc_sparring',name:'',profile:finalProfile},{code:'aeson_duel',name:'',owner_character_id:ch.id}])]);
  await c.execute('INSERT INTO player_worldtree_duels (session_id,owner_character_id,participants_json) VALUES (?,?,?)',[session,ch.id,JSON.stringify(refreshed.map(m=>({id:Number(m.id),name:String(m.name),hp:Number(m.current_hp),mp:Number(m.current_mp)})))]);
  await recordCharacterOperation(c,{characterId:Number(ch.id),kind:'combat.story_duel_started',source:{system:'worldtree_duel',id:session,step:'started'},outcome:'开始',summary:'开始艾森的约战',detail:{sessionId:session,participantIds:refreshed.map(m=>Number(m.id))}});
  await resetCardMovementCharge(c,refreshed.map(member=>Number(member.id)));
  await c.execute("INSERT INTO combat_sessions (id,character_id,spawn_id,player_hp,player_mp,cooldowns,opening_damage_bonus,mode) VALUES (?,?,?,?,?,JSON_OBJECT(),0,'story')",[session,ch.id,spawn.insertId,ch.current_hp,ch.current_mp]);
  for(const member of refreshed){await c.execute('INSERT INTO combat_members (session_id,character_id,current_hp,current_mp,selected_target_id,cooldowns,stamina_eligible) VALUES (?,?,?,?,?,JSON_OBJECT(),0)',[session,member.id,member.current_hp,member.current_mp,spawn.insertId]);await c.execute('INSERT INTO combat_threat (session_id,spawn_id,character_id,threat) VALUES (?,?,?,1)',[session,spawn.insertId,member.id]);}
  const[professions]=await c.execute<RowDataPacket[]>(`SELECT character_id,profession_code FROM player_advanced_professions WHERE character_id IN (${refreshed.map(()=>'?').join(',')})`,refreshed.map(member=>member.id));
  for(const profession of professions){const resource=advancedResourceForProfession(String(profession.profession_code));if(resource)await c.execute('INSERT INTO combat_profession_resources (session_id,character_id,profession_code,resource_code,resource_name,current_value,max_value) VALUES (?,?,?,?,?,0,100)',[session,profession.character_id,profession.profession_code,resource.code,resource.name]);}
  await c.execute('INSERT INTO combat_targets (session_id,spawn_id,current_mp,cooldowns) VALUES (?,?,?,JSON_OBJECT())',[session,spawn.insertId,finalProfile.stats.mpMax]);await snapshotCombatEnvironment(c,session,Number(ch.current_region_id),refreshed.map(m=>Number(m.id)));
  return{sessionId:session,text:'艾森把力量压制符带扣紧，向我和队友招手。看台上的艾薇儿双手拢在嘴边：“小心他的寸劲！哥，你也不许耍赖！”艾森哼笑一声，脚下白砂猛地散开。'};});

export const finishAesonDuel=async(c:PoolConnection,session:string,result:'victory'|'defeat'|'escaped'|'timeout')=>{const[rows]=await c.execute<RowDataPacket[]>('SELECT * FROM player_worldtree_duels WHERE session_id=? FOR UPDATE',[session]);const row=rows[0];if(!row)return null;if(row.state!=='active')return '这场约战已结算。';const participants=typeof row.participants_json==='string'?JSON.parse(row.participants_json):row.participants_json;
  await c.execute('UPDATE player_worldtree_duels SET state=?,finished_at=NOW() WHERE session_id=?',[result,session]);if(result==='victory')await writeStage(c,Number(row.owner_character_id),challengeCode,4);
  const[tree]=await c.execute<RowDataPacket[]>("SELECT id FROM map_regions WHERE code='world_tree' LIMIT 1",[]);if(!tree[0])throw new Error('世界树归途暂不可用。');for(const m of participants)await c.execute('UPDATE characters SET current_region_id=?,pos_x=6,pos_y=-4,pos_z=0,current_hp=LEAST(hp_max,?),current_mp=LEAST(mp_max,?),activity_status=\'active\' WHERE id=?',[tree[0].id,m.hp,m.mp,m.id]);
  await c.execute('UPDATE combat_sessions SET state=? WHERE id=?',[result==='timeout'?'escaped':result,session]);await c.execute('DELETE FROM combat_status_effects WHERE session_id=?',[session]);await c.execute('DELETE FROM combat_spirits WHERE session_id=?',[session]);await c.execute('UPDATE combat_members SET pending_action=NULL WHERE session_id=?',[session]);await c.execute("UPDATE monster_spawns s JOIN combat_targets t ON t.spawn_id=s.id SET s.current_hp=0,s.defeated_at=NOW(),s.traits_json=JSON_ARRAY(JSON_OBJECT('code','aeson_duel','name','')) WHERE t.session_id=?",[session]);
  for(const participant of participants)await recordCharacterOperation(c,{characterId:Number(participant.id),kind:`combat.story_duel.${result}`,source:{system:'worldtree_duel',id:session,step:`settled:${participant.id}`},outcome:result,summary:`艾森约战${result==='victory'?'胜利':result==='defeat'?'落败':'结束'}`,detail:{sessionId:session,ownerCharacterId:Number(row.owner_character_id),participantId:Number(participant.id),result},scoreKey:`aeson_duel:${row.owner_character_id}`});
  return result==='victory'?aesonVictory(String(participants.find((m:any)=>Number(m.id)===Number(row.owner_character_id))?.name??'你')):'我没能赢下这场约战。艾森在最后一拳前收住力，把我和队友送到场边。艾薇儿先跑来确认我们没有受伤，才叉着腰骂哥哥：“你赢了也不准摆臭脸！”医师替我们处理伤口。艾森仍等在竞技场里，约战可以准备好后重试。';};
