import type { Pool } from 'mysql2/promise';
import { hiddenProfessions, hiddenSkills, hiddenPassiveCode, hiddenProfessionsReleased } from '../game/hidden-profession.config';

/** 幂等扩展。独立任务表不会被公共任务列表读取，不修改历史普通二转进度。 */
export const initializeHiddenProfessions = async (pool: Pool, validateBeforeRelease = false) => {
  if (!hiddenProfessionsReleased && !validateBeforeRelease) return;
  await pool.query('CREATE TABLE IF NOT EXISTS player_hidden_profession_quests (character_id BIGINT UNSIGNED NOT NULL, profession_code VARCHAR(40) NOT NULL, stage TINYINT UNSIGNED NOT NULL DEFAULT 1, accepted_at DATETIME NULL, materials_paid TINYINT NOT NULL DEFAULT 0, evidence_json JSON NULL, completed_json JSON NULL, qualified_at DATETIME NULL, revision INT UNSIGNED NOT NULL DEFAULT 0, PRIMARY KEY(character_id,profession_code), CONSTRAINT fk_hidden_quest_character FOREIGN KEY(character_id) REFERENCES characters(id) ON DELETE CASCADE) ENGINE=InnoDB');
  await pool.query('CREATE TABLE IF NOT EXISTS player_hidden_profession_loadouts (character_id BIGINT UNSIGNED NOT NULL, profession_code VARCHAR(40) NOT NULL, config_json JSON NOT NULL, revision INT UNSIGNED NOT NULL DEFAULT 0, PRIMARY KEY(character_id,profession_code), CONSTRAINT fk_hidden_loadout_character FOREIGN KEY(character_id) REFERENCES characters(id) ON DELETE CASCADE) ENGINE=InnoDB');
  await pool.query('CREATE TABLE IF NOT EXISTS player_hidden_action_drafts (character_id BIGINT UNSIGNED NOT NULL, battle_key VARCHAR(100) NOT NULL, turn_no INT UNSIGNED NOT NULL, skill_code VARCHAR(80) NOT NULL, draft_json JSON NOT NULL, revision INT UNSIGNED NOT NULL DEFAULT 0, submitted TINYINT NOT NULL DEFAULT 0, PRIMARY KEY(character_id,battle_key,turn_no), CONSTRAINT fk_hidden_draft_character FOREIGN KEY(character_id) REFERENCES characters(id) ON DELETE CASCADE) ENGINE=InnoDB');
  for (const skill of hiddenSkills) {
    const category = skill.profession === 'weapon_master' && skill.power > 0 ? 'physical' : skill.power > 0 ? 'magic' : 'utility';
    await pool.execute("INSERT INTO skill_definitions (code,name,category,tier,skill_kind,damage_type,element,range_type,target_scope,mana_cost,base_mana_cost,cooldown_turns,power,max_level,learn_cost,upgrade_cost,chant_turns,description) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,1,0,1,0,?) ON DUPLICATE KEY UPDATE name=VALUES(name),category=VALUES(category),tier=VALUES(tier),mana_cost=VALUES(mana_cost),base_mana_cost=VALUES(base_mana_cost),cooldown_turns=VALUES(cooldown_turns),power=VALUES(power),max_level=1,description=VALUES(description)",
      [skill.code, skill.name, category, skill.tier, category === 'physical' ? '斩击' : '奥术', category === 'physical' ? '斩击' : '奥术', '无', '远程', '单体', skill.mana, category === 'physical' ? skill.mana / .4 : skill.mana, skill.cooldown, skill.power, skill.description]);
  }
  for (const profession of hiddenProfessions) await pool.execute("INSERT INTO skill_definitions (code,name,category,tier,max_level,learn_cost,upgrade_cost,description,passive_effect_json) VALUES (?,?,'bound','中位',1,0,1,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),passive_effect_json=VALUES(passive_effect_json)",
    [hiddenPassiveCode(profession.code), profession.passive, profession.role + '。本职传承：' + profession.inheritance + '。', JSON.stringify({ hiddenProfession: 1 })]);
  await pool.execute("INSERT INTO item_definitions (code,name,item_type,item_category,description,trade_price,weight,obtain_source) SELECT 'wind_element_dust','风元素微尘',water_dust.item_type,water_dust.item_category,'轻盈流动的风相粒子，用于调配扩散反应。',3,0.03,'解构师分解' FROM item_definitions AS water_dust WHERE water_dust.code='water_element_dust' LIMIT 1 ON DUPLICATE KEY UPDATE name=VALUES(name),item_type=VALUES(item_type),description=VALUES(description),obtain_source=VALUES(obtain_source)");
};

